// Verification of candidate songs
const candidates = [
  { artist: 'Jeff Satur', en: 'Fade', query: 'Jeff Satur Fade official mv' },
  { artist: 'Jeff Satur', en: 'Hide', query: 'Jeff Satur Hide official mv' },
  { artist: 'Jeff Satur', en: "Why Don't You Stay", query: "Jeff Satur Why Don't You Stay official mv" },
  { artist: 'PROXIE', en: 'Silent Mode', query: 'PROXIE Silent Mode official mv' },
  { artist: 'PROXIE', en: 'STOP!', query: 'PROXIE STOP! official mv' },
  { artist: 'PROXIE', en: 'TRAFFIC', query: 'PROXIE TRAFFIC official mv' },
  { artist: 'PROXIE', en: 'Crazy Love', query: 'PROXIE Crazy Love official mv' },
  { artist: 'PiXXiE', en: 'Whatever', query: 'PiXXiE Whatever official mv' },
  { artist: 'Fellow Fellow', en: 'Bloom', query: 'fellow fellow Bloom official mv' },
  { artist: 'Fellow Fellow', en: 'Proud', query: 'fellow fellow Proud official mv' },
  { artist: 'Bell Warisara', en: 'Million Butterflies', query: 'เบล วริศรา Million Butterflies official mv' },
  { artist: 'Tilly Birds', en: 'Like a Dead Man', query: 'Tilly Birds Like a Dead Man official mv' },
  { artist: 'Bodyslam', en: 'Sticker', query: 'Bodyslam Sticker official mv' },
  { artist: 'Palmy', en: 'Tick Tock', query: 'ปาล์มมี่ Tick Tock official mv' },
  { artist: 'PP Krit', en: 'Hesitate', query: 'PP Krit Hesitate official mv' },
  { artist: 'Billkin', en: 'A Beautiful Ride', query: 'Billkin A Beautiful Ride official mv' },
  { artist: 'Television Off', en: 'Be My Youth', query: 'Television Off Be My Youth official mv' },
  { artist: 'Television Off', en: 'Mantis', query: 'Television Off Mantis official mv' },
  { artist: 'Television Off', en: 'TV Show', query: 'Television Off TV Show official mv' },
  { artist: 'Television Off', en: 'do you?', query: 'Television Off do you? official mv' },
  { artist: 'Television Off', en: "22, I'll be missing you.", query: "Television Off 22, I'll be missing you official mv" },
  { artist: 'Television Off', en: "Sigmas don't cry", query: "Television Off Sigmas don't cry official mv" },
  { artist: 'Landokmai', en: 'On the Train', query: 'Landokmai On the Train official mv' },
  { artist: 'Landokmai', en: 'The Diary', query: 'Landokmai The Diary official mv' },
  { artist: 'Landokmai', en: 'Please be true', query: 'Landokmai Please be true official mv' },
  { artist: 'Landokmai', en: 'Our Sunset', query: 'Landokmai Our Sunset official mv' },
  { artist: 'Landokmai', en: 'A song on the radio', query: 'Landokmai A song on the radio official mv' },
  { artist: 'The Yers', en: 'Dance in the Dark', query: 'The Yers Dance in the Dark official mv' },
  { artist: 'Anatomy Rabbit', en: 'Are You out yet ?', query: 'Anatomy Rabbit Are You out yet official mv' },
  { artist: 'bamm', en: "Sad O'Clock", query: "bamm Sad O'Clock official mv" },
  { artist: 'bamm', en: 'Curse', query: 'bamm Curse official mv' },
  { artist: 'NONT TANONT', en: 'Memories', query: 'NONT TANONT Memories official mv' },
  { artist: 'QLER', en: '30 cm', query: 'QLER 30 cm official mv' },
  { artist: 'Txrbo', en: "Can't Take It Anymore", query: "Txrbo Can't Take It Anymore official mv" },
  { artist: 'YourMOOD', en: 'Your Guy', query: 'YourMOOD Your Guy official mv' },
  { artist: 'Mild', en: 'I Do Miss You', query: 'Mild I Do Miss You official mv' },
  { artist: 'Scrubb', en: 'Inchan Tree', query: 'Scrubb Inchan Tree official mv' },
  { artist: 'Scrubb', en: 'Surfing', query: 'Scrubb Surfing official mv' },
  { artist: 'Scrubb', en: 'Everyday', query: 'Scrubb Everyday official mv' },
  { artist: 'Loserpop', en: 'Once', query: 'Loserpop Once official mv' },
  { artist: 'Loserpop', en: 'Good Old Days', query: 'Loserpop Good Old Days official mv' },
  { artist: 'Loserpop', en: 'Still', query: 'Loserpop Still official mv' },
];

console.log(`Total verified candidates to check: ${candidates.length}`);
