import * as fs from 'fs';
import { THAI_SONG_TRANSLATION_RULES, THAI_SONG_BIDIRECTIONAL_ALIASES } from '../src/data/thaiSongTitleAliases';

// New candidate rules to add
export const NEW_RULES: Record<string, { canonical: string; artists?: string[] }> = {
  // Jeff Satur
  'ghost': { canonical: 'ซ่อน (ไม่) หา (Ghost)', artists: ['jeff satur', 'jeffsatur'] },
  'ซ่อน (ไม่) หา': { canonical: 'ซ่อน (ไม่) หา (Ghost)', artists: ['jeff satur', 'jeffsatur'] },
  'ซ่อนไม่หา': { canonical: 'ซ่อน (ไม่) หา (Ghost)', artists: ['jeff satur', 'jeffsatur'] },
  'yellow leaf': { canonical: 'ส่วนน้อย (Yellow Leaf)', artists: ['jeff satur', 'jeffsatur'] },
  'yellowleaf': { canonical: 'ส่วนน้อย (Yellow Leaf)', artists: ['jeff satur', 'jeffsatur'] },
  'ส่วนน้อย': { canonical: 'ส่วนน้อย (Yellow Leaf)', artists: ['jeff satur', 'jeffsatur'] },

  // Anatomy Rabbit
  'kab rod len': { canonical: 'ขับรถเล่น (Kab Rod Len)', artists: ['anatomy rabbit'] },
  'kabrodlen': { canonical: 'ขับรถเล่น (Kab Rod Len)', artists: ['anatomy rabbit'] },
  'ขับรถเล่น': { canonical: 'ขับรถเล่น (Kab Rod Len)', artists: ['anatomy rabbit'] },
  'mars loner': { canonical: 'สภาวะเดียวดายบนดาวอังคาร (Mars Loner)', artists: ['anatomy rabbit'] },
  'marsloner': { canonical: 'สภาวะเดียวดายบนดาวอังคาร (Mars Loner)', artists: ['anatomy rabbit'] },
  'สภาวะเดียวดายบนดาวอังคาร': { canonical: 'สภาวะเดียวดายบนดาวอังคาร (Mars Loner)', artists: ['anatomy rabbit'] },
  'udon town': { canonical: 'อุดรทาวน์ (Udon Town)', artists: ['anatomy rabbit'] },
  'udontown': { canonical: 'อุดรทาวน์ (Udon Town)', artists: ['anatomy rabbit'] },
  'อุดรทาวน์': { canonical: 'อุดรทาวน์ (Udon Town)', artists: ['anatomy rabbit'] },

  // Safeplanet (additional verified tracks from album)
  'the heart': { canonical: 'ในเมื่อใจ (The Heart)', artists: ['safeplanet'] },
  'theheart': { canonical: 'ในเมื่อใจ (The Heart)', artists: ['safeplanet'] },
  'ในเมื่อใจ': { canonical: 'ในเมื่อใจ (The Heart)', artists: ['safeplanet'] },
  'my worry': { canonical: 'รู้เธอยังกังวล (My Worry)', artists: ['safeplanet'] },
  'myworry': { canonical: 'รู้เธอยังกังวล (My Worry)', artists: ['safeplanet'] },
  'รู้เธอยังกังวล': { canonical: 'รู้เธอยังกังวล (My Worry)', artists: ['safeplanet'] },
  'new world': { canonical: 'โลกใบใหม่ (New World)', artists: ['safeplanet'] },
  'newworld': { canonical: 'โลกใบใหม่ (New World)', artists: ['safeplanet'] },
  'โลกใบใหม่': { canonical: 'โลกใบใหม่ (New World)', artists: ['safeplanet'] },

  // YOUNGOHM
  'cold fire': { canonical: 'ไฟเย็น (Cold Fire)', artists: ['youngohm'] },
  'coldfire': { canonical: 'ไฟเย็น (Cold Fire)', artists: ['youngohm'] },
  'ไฟเย็น': { canonical: 'ไฟเย็น (Cold Fire)', artists: ['youngohm'] },
  'warm up a curry': { canonical: 'อุ่นแกง (Warm up a Curry)', artists: ['youngohm'] },
  'warmupacurry': { canonical: 'อุ่นแกง (Warm up a Curry)', artists: ['youngohm'] },
  'อุ่นแกง': { canonical: 'อุ่นแกง (Warm up a Curry)', artists: ['youngohm'] },
  'legends of a love story': { canonical: 'เรื่องราวความรักในตำนาน (Legends of a Love Story)', artists: ['youngohm'] },
  'legendsofalovestory': { canonical: 'เรื่องราวความรักในตำนาน (Legends of a Love Story)', artists: ['youngohm'] },
  'เรื่องราวความรักในตำนาน': { canonical: 'เรื่องราวความรักในตำนาน (Legends of a Love Story)', artists: ['youngohm'] },
  'the last kiss': { canonical: 'จูบลา (The Last Kiss)', artists: ['youngohm'] },
  'thelastkiss': { canonical: 'จูบลา (The Last Kiss)', artists: ['youngohm'] },
  'จูบลา': { canonical: 'จูบลา (The Last Kiss)', artists: ['youngohm'] },
  'the light in the city (intro)': { canonical: 'แสงไฟ (The Light in the City)', artists: ['youngohm'] },
  'the light in the city': { canonical: 'แสงไฟ (The Light in the City)', artists: ['youngohm'] },
  'แสงไฟ': { canonical: 'แสงไฟ (The Light in the City)', artists: ['youngohm'] },
  'keep going': { canonical: 'เดินต่อไป (Keep Going)', artists: ['youngohm'] },
  'keepgoing': { canonical: 'เดินต่อไป (Keep Going)', artists: ['youngohm'] },
  'เดินต่อไป': { canonical: 'เดินต่อไป (Keep Going)', artists: ['youngohm'] },
  'nakorn dara': { canonical: 'นครดารา (Nakorn Dara)', artists: ['youngohm'] },
  'nakorndara': { canonical: 'นครดารา (Nakorn Dara)', artists: ['youngohm'] },
  'นครดารา': { canonical: 'นครดารา (Nakorn Dara)', artists: ['youngohm'] },

  // 4EVE
  'test me': { canonical: 'วัดปะหล่ะ? (TEST ME)', artists: ['4eve'] },
  'testme': { canonical: 'วัดปะหล่ะ? (TEST ME)', artists: ['4eve'] },
  'วัดปะหล่ะ': { canonical: 'วัดปะหล่ะ? (TEST ME)', artists: ['4eve'] },
  'วัดปะหล่ะ?': { canonical: 'วัดปะหล่ะ? (TEST ME)', artists: ['4eve'] },
  'วัดป่ะหล่ะ': { canonical: 'วัดปะหล่ะ? (TEST ME)', artists: ['4eve'] },
  'วัดป่ะหล่ะ?': { canonical: 'วัดปะหล่ะ? (TEST ME)', artists: ['4eve'] },
  'exceptional': { canonical: 'ข้อยกเว้น (Exceptional)', artists: ['4eve'] },
  'ข้อยกเว้น': { canonical: 'ข้อยกเว้น (Exceptional)', artists: ['4eve'] },
  'less is more': { canonical: 'สิ่งเล็กน้อย (LESS IS MORE)', artists: ['4eve'] },
  'lessismore': { canonical: 'สิ่งเล็กน้อย (LESS IS MORE)', artists: ['4eve'] },
  'สิ่งเล็กน้อย': { canonical: 'สิ่งเล็กน้อย (LESS IS MORE)', artists: ['4eve'] },
  'หยดน้ำตา': { canonical: 'หยดน้ำตา (TEARS)', artists: ['4eve'] },
  'not kidding': { canonical: 'ไปล้อเล่นไกลๆ (Not Kidding)', artists: ['4eve'] },
  'notkidding': { canonical: 'ไปล้อเล่นไกลๆ (Not Kidding)', artists: ['4eve'] },
  'ไปล้อเล่นไกลๆ': { canonical: 'ไปล้อเล่นไกลๆ (Not Kidding)', artists: ['4eve'] },
  'our first day': { canonical: 'วันแรกของวันที่เหลือ (Our First Day)', artists: ['4eve'] },
  'ourfirstday': { canonical: 'วันแรกของวันที่เหลือ (Our First Day)', artists: ['4eve'] },
  'วันแรกของวันที่เหลือ': { canonical: 'วันแรกของวันที่เหลือ (Our First Day)', artists: ['4eve'] },

  // PiXXiE
  'too cute': { canonical: 'เกินต้าน (Too Cute)', artists: ['pixxie'] },
  'toocute': { canonical: 'เกินต้าน (Too Cute)', artists: ['pixxie'] },
  'เกินต้าน': { canonical: 'เกินต้าน (Too Cute)', artists: ['pixxie'] },
  'mutelu': { canonical: 'มูเตลู (MUTELU)', artists: ['pixxie'] },
  'มูเตลู': { canonical: 'มูเตลู (MUTELU)', artists: ['pixxie'] },
  'ded': { canonical: 'เด็ด (DED)', artists: ['pixxie'] },
  'เด็ด': { canonical: 'เด็ด (DED)', artists: ['pixxie'] },
  'boo': { canonical: 'งอนละ (Boo)', artists: ['pixxie'] },
  'งอนละ': { canonical: 'งอนละ (Boo)', artists: ['pixxie'] },
  'pixxel': { canonical: 'เพลงประจำวัน (PiXXeL)', artists: ['pixxie'] },
  'เพลงประจำวัน': { canonical: 'เพลงประจำวัน (PiXXeL)', artists: ['pixxie'] },
  'too late': { canonical: 'รักกันตอนเลิกกัน (Too Late)', artists: ['pixxie'] },
  'toolate': { canonical: 'รักกันตอนเลิกกัน (Too Late)', artists: ['pixxie'] },
  'รักกันตอนเลิกกัน': { canonical: 'รักกันตอนเลิกกัน (Too Late)', artists: ['pixxie'] },
  'infinity': { canonical: 'ตลอดไปยังไม่พอ (Infinity)', artists: ['pixxie'] },
  'ตลอดไปยังไม่พอ': { canonical: 'ตลอดไปยังไม่พอ (Infinity)', artists: ['pixxie'] },

  // bamm
  '2cool2care': { canonical: 'โดนเทแต่เท่อยู่ (2cool2care)', artists: ['bamm'] },
  'โดนเทแต่เท่อยู่': { canonical: 'โดนเทแต่เท่อยู่ (2cool2care)', artists: ['bamm'] },
  'woof': { canonical: 'เอ๋ง (WOOF)', artists: ['bamm'] },
  'เอ๋ง': { canonical: 'เอ๋ง (WOOF)', artists: ['bamm'] },
  'unfriend zone': { canonical: 'ใครเพื่อนแก (Unfriend Zone)', artists: ['bamm'] },
  'unfriendzone': { canonical: 'ใครเพื่อนแก (Unfriend Zone)', artists: ['bamm'] },
  'ใครเพื่อนแก': { canonical: 'ใครเพื่อนแก (Unfriend Zone)', artists: ['bamm'] },
  'close friend': { canonical: 'เพื่อนกันไม่เลิกกัน (Close Friend)', artists: ['bamm'] },
  'closefriend': { canonical: 'เพื่อนกันไม่เลิกกัน (Close Friend)', artists: ['bamm'] },
  'เพื่อนกันไม่เลิกกัน': { canonical: 'เพื่อนกันไม่เลิกกัน (Close Friend)', artists: ['bamm'] },
  'close enough': { canonical: 'เกือบเป็นแฟน (Close Enough)', artists: ['bamm'] },
  'closeenough': { canonical: 'เกือบเป็นแฟน (Close Enough)', artists: ['bamm'] },
  'เกือบเป็นแฟน': { canonical: 'เกือบเป็นแฟน (Close Enough)', artists: ['bamm'] },
  'bammboo': { canonical: 'เธอเก่งที่สุดแล้ว (bammBOO)', artists: ['bamm'] },
  'เธอเก่งที่สุดแล้ว': { canonical: 'เธอเก่งที่สุดแล้ว (bammBOO)', artists: ['bamm'] },
  'rookie lover': { canonical: 'มือสมัครรัก (Rookie Lover)', artists: ['bamm'] },
  'rookielover': { canonical: 'มือสมัครรัก (Rookie Lover)', artists: ['bamm'] },
  'มือสมัครรัก': { canonical: 'มือสมัครรัก (Rookie Lover)', artists: ['bamm'] },

  // PROXIE
  'unnoticed': { canonical: 'ที่ไม่รัก (Unnoticed)', artists: ['proxie'] },
  'ที่ไม่รัก': { canonical: 'ที่ไม่รัก (Unnoticed)', artists: ['proxie'] },
  'blurrr': { canonical: 'สถานะเบลอ (Blurrr)', artists: ['proxie'] },
  'blur': { canonical: 'สถานะเบลอ (Blurrr)', artists: ['proxie'] },
  'สถานะเบลอ': { canonical: 'สถานะเบลอ (Blurrr)', artists: ['proxie'] },
  'hurting': { canonical: 'เจ็บอยู่ (Hurting)', artists: ['proxie'] },
  'เจ็บอยู่': { canonical: 'เจ็บอยู่ (Hurting)', artists: ['proxie'] },
  'lonely boy': { canonical: 'เหงาอย่างนี้สินะ (Lonely Boy)', artists: ['proxie'] },
  'lonelyboy': { canonical: 'เหงาอย่างนี้สินะ (Lonely Boy)', artists: ['proxie'] },
  'เหงาอย่างนี้สินะ': { canonical: 'เหงาอย่างนี้สินะ (Lonely Boy)', artists: ['proxie'] },
  'crush': { canonical: 'ชน (Crush)', artists: ['proxie'] },
  'ชน': { canonical: 'ชน (Crush)', artists: ['proxie'] },
  'if i could': { canonical: 'เริ่มก่อน (If I Could)', artists: ['proxie'] },
  'ificould': { canonical: 'เริ่มก่อน (If I Could)', artists: ['proxie'] },
  'เริ่มก่อน': { canonical: 'เริ่มก่อน (If I Could)', artists: ['proxie'] },

  // BUS
  'no matter what': { canonical: 'แค่ไหนแค่นั้น (NO MATTER WHAT)', artists: ['bus'] },
  'nomatterwhat': { canonical: 'แค่ไหนแค่นั้น (NO MATTER WHAT)', artists: ['bus'] },
  'แค่ไหนแค่นั้น': { canonical: 'แค่ไหนแค่นั้น (NO MATTER WHAT)', artists: ['bus'] },
  'brother zone': { canonical: 'แค่น้องชาย (brother zone)', artists: ['bus'] },
  'brotherzone': { canonical: 'แค่น้องชาย (brother zone)', artists: ['bus'] },
  'แค่น้องชาย': { canonical: 'แค่น้องชาย (brother zone)', artists: ['bus'] },
  'happily missing you': { canonical: 'สุขสันต์วันคิดถึง (Happily Missing You)', artists: ['bus'] },
  'happilymissingyou': { canonical: 'สุขสันต์วันคิดถึง (Happily Missing You)', artists: ['bus'] },
  'สุขสันต์วันคิดถึง': { canonical: 'สุขสันต์วันคิดถึง (Happily Missing You)', artists: ['bus'] },

  // Billkin & PP Krit
  'skyline': { canonical: 'กีดกัน (Skyline)', artists: ['billkin'] },
  'กีดกัน': { canonical: 'กีดกัน (Skyline)', artists: ['billkin'] },
  'cant translate': { canonical: 'แปลไม่ออก (Can\'t Translate)', artists: ['billkin'] },
  'can\'t translate': { canonical: 'แปลไม่ออก (Can\'t Translate)', artists: ['billkin'] },
  'canttranslate': { canonical: 'แปลไม่ออก (Can\'t Translate)', artists: ['billkin'] },
  'แปลไม่ออก': { canonical: 'แปลไม่ออก (Can\'t Translate)', artists: ['billkin'] },
  'special one': { canonical: 'โคตรพิเศษ (Special One)', artists: ['billkin'] },
  'specialone': { canonical: 'โคตรพิเศษ (Special One)', artists: ['billkin'] },
  'โคตรพิเศษ': { canonical: 'โคตรพิเศษ (Special One)', artists: ['billkin'] },
  'safe zone': { canonical: 'รู้งี้เป็นแฟนกันตั้งนานแล้ว (Safe Zone)', artists: ['billkin', 'pp krit', 'pp'] },
  'safezone': { canonical: 'รู้งี้เป็นแฟนกันตั้งนานแล้ว (Safe Zone)', artists: ['billkin', 'pp krit', 'pp'] },
  'รู้งี้เป็นแฟนกันตั้งนานแล้ว': { canonical: 'รู้งี้เป็นแฟนกันตั้งนานแล้ว (Safe Zone)', artists: ['billkin', 'pp krit', 'pp'] },
  'coming of age': { canonical: 'ไม่ปล่อยมือ (Coming of Age)', artists: ['billkin', 'pp krit', 'pp'] },
  'comingofage': { canonical: 'ไม่ปล่อยมือ (Coming of Age)', artists: ['billkin', 'pp krit', 'pp'] },
  'ไม่ปล่อยมือ': { canonical: 'ไม่ปล่อยมือ (Coming of Age)', artists: ['billkin', 'pp krit', 'pp'] },
  'i like us': { canonical: 'ชอบตัวเองตอนอยู่กับเธอ (I Like Us)', artists: ['billkin'] },
  'ilikeus': { canonical: 'ชอบตัวเองตอนอยู่กับเธอ (I Like Us)', artists: ['billkin'] },
  'ชอบตัวเองตอนอยู่กับเธอ': { canonical: 'ชอบตัวเองตอนอยู่กับเธอ (I Like Us)', artists: ['billkin'] },
  'please please': { canonical: 'กลับมาคบกันเถอะ (Please Please)', artists: ['billkin'] },
  'pleaseplease': { canonical: 'กลับมาคบกันเถอะ (Please Please)', artists: ['billkin'] },
  'กลับมาคบกันเถอะ': { canonical: 'กลับมาคบกันเถอะ (Please Please)', artists: ['billkin'] },
  'ooh!': { canonical: 'เสนอตัว (Ooh!)', artists: ['pp krit', 'pp'] },
  'ooh': { canonical: 'เสนอตัว (Ooh!)', artists: ['pp krit', 'pp'] },
  'เสนอตัว': { canonical: 'เสนอตัว (Ooh!)', artists: ['pp krit', 'pp'] },

  // Ink Waruntorn
  'insomnia': { canonical: 'เหงา เหงา (Insomnia)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'เหงาเหงา': { canonical: 'เหงา เหงา (Insomnia)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'เหงา เหงา': { canonical: 'เหงา เหงา (Insomnia)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'glad': { canonical: 'ดีใจด้วยนะ (Glad)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'ดีใจด้วยนะ': { canonical: 'ดีใจด้วยนะ (Glad)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'stay': { canonical: 'รอหรือพอ (Stay)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'รอหรือพอ': { canonical: 'รอหรือพอ (Stay)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'call me': { canonical: 'ไม่อยากเหงาแล้ว (Call Me)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'callme': { canonical: 'ไม่อยากเหงาแล้ว (Call Me)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'ไม่อยากเหงาแล้ว': { canonical: 'ไม่อยากเหงาแล้ว (Call Me)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'expert': { canonical: 'เก่งแต่เรื่องคนอื่น (Expert)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'เก่งแต่เรื่องคนอื่น': { canonical: 'เก่งแต่เรื่องคนอื่น (Expert)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'eyes dont lie': { canonical: 'สายตาหลอกกันไม่ได้ (Eyes Don\'t Lie)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'eyes don\'t lie': { canonical: 'สายตาหลอกกันไม่ได้ (Eyes Don\'t Lie)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'eyesdontlie': { canonical: 'สายตาหลอกกันไม่ได้ (Eyes Don\'t Lie)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'สายตาหลอกกันไม่ได้': { canonical: 'สายตาหลอกกันไม่ได้ (Eyes Don\'t Lie)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'repeat': { canonical: 'อยากเริ่มต้นใหม่กับคนเดิม (Repeat)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'อยากเริ่มต้นใหม่กับคนเดิม': { canonical: 'อยากเริ่มต้นใหม่กับคนเดิม (Repeat)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'i like myself the most': { canonical: 'ชอบอยู่คนเดียว (I Like Myself The Most)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'ilikemyselfthemost': { canonical: 'ชอบอยู่คนเดียว (I Like Myself The Most)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'ชอบอยู่คนเดียว': { canonical: 'ชอบอยู่คนเดียว (I Like Myself The Most)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'close': { canonical: 'คนใหม่เขาดูแลอยู่ (Close)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },
  'คนใหม่เขาดูแลอยู่': { canonical: 'คนใหม่เขาดูแลอยู่ (Close)', artists: ['ink waruntorn', 'อิ้งค์ วรันธร', 'ink'] },

  // Three Man Down
  'city': { canonical: 'ข้างกัน (City)', artists: ['three man down'] },
  'ข้างกัน': { canonical: 'ข้างกัน (City)', artists: ['three man down'] },
  'hey josh': { canonical: 'Hey Josh! (พรุ่งนี้ต้องลืมเธอ)', artists: ['three man down'] },
  'hey josh!': { canonical: 'Hey Josh! (พรุ่งนี้ต้องลืมเธอ)', artists: ['three man down'] },
  'heyjosh': { canonical: 'Hey Josh! (พรุ่งนี้ต้องลืมเธอ)', artists: ['three man down'] },
  'พรุ่งนี้ต้องลืมเธอ': { canonical: 'Hey Josh! (พรุ่งนี้ต้องลืมเธอ)', artists: ['three man down'] },
  'wasted': { canonical: 'ของที่เธอไม่ต้องการ (Wasted)', artists: ['three man down'] },
  'ของที่เธอไม่ต้องการ': { canonical: 'ของที่เธอไม่ต้องการ (Wasted)', artists: ['three man down'] },
  'platonic love': { canonical: 'เพื่อนสนิท (Platonic Love)', artists: ['three man down'] },
  'platoniclove': { canonical: 'เพื่อนสนิท (Platonic Love)', artists: ['three man down'] },
  'เพื่อนสนิท': { canonical: 'เพื่อนสนิท (Platonic Love)', artists: ['three man down'] },

  // Tilly Birds
  'cant keep up': { canonical: 'ลู่วิ่ง (Can\'t Keep Up)', artists: ['tilly birds'] },
  'can\'t keep up': { canonical: 'ลู่วิ่ง (Can\'t Keep Up)', artists: ['tilly birds'] },
  'cantkeepup': { canonical: 'ลู่วิ่ง (Can\'t Keep Up)', artists: ['tilly birds'] },
  'ลู่วิ่ง': { canonical: 'ลู่วิ่ง (Can\'t Keep Up)', artists: ['tilly birds'] },
  'baggage': { canonical: 'เดอะแบก (Baggage)', artists: ['tilly birds'] },
  'เดอะแบก': { canonical: 'เดอะแบก (Baggage)', artists: ['tilly birds'] },
  'slipped your mind': { canonical: 'จำเก่ง (Slipped Your Mind)', artists: ['tilly birds', 'f.hero'] },
  'slippedyourmind': { canonical: 'จำเก่ง (Slipped Your Mind)', artists: ['tilly birds', 'f.hero'] },
  'จำเก่ง': { canonical: 'จำเก่ง (Slipped Your Mind)', artists: ['tilly birds', 'f.hero'] },
  'bangkok winter': { canonical: 'ฤดูหนาว (Bangkok Winter)', artists: ['tilly birds', 'paam'] },
  'bangkokwinter': { canonical: 'ฤดูหนาว (Bangkok Winter)', artists: ['tilly birds', 'paam'] },
  'ฤดูหนาว': { canonical: 'ฤดูหนาว (Bangkok Winter)', artists: ['tilly birds', 'paam'] },
  'the one': { canonical: 'ผู้เดียว (The One)', artists: ['tilly birds'] },
  'theone': { canonical: 'ผู้เดียว (The One)', artists: ['tilly birds'] },
  'ผู้เดียว': { canonical: 'ผู้เดียว (The One)', artists: ['tilly birds'] },
  'cut me off': { canonical: 'อย่าพี่น้อง (Cut Me Off)', artists: ['tilly birds'] },
  'cutmeoff': { canonical: 'อย่าพี่น้อง (Cut Me Off)', artists: ['tilly birds'] },
  'อย่าพี่น้อง': { canonical: 'อย่าพี่น้อง (Cut Me Off)', artists: ['tilly birds'] },

  // POLYCAT
  'forever mate': { canonical: 'เพื่อนไม่จริง (Forever Mate)', artists: ['polycat'] },
  'forevermate': { canonical: 'เพื่อนไม่จริง (Forever Mate)', artists: ['polycat'] },
  'เพื่อนไม่จริง': { canonical: 'เพื่อนไม่จริง (Forever Mate)', artists: ['polycat'] },
  'faith': { canonical: 'ภักดี (Faith)', artists: ['polycat'] },
  'ภักดี': { canonical: 'ภักดี (Faith)', artists: ['polycat'] },
  'goodfella': { canonical: 'เพื่อนพระเอก (Goodfella)', artists: ['polycat'] },
  'เพื่อนพระเอก': { canonical: 'เพื่อนพระเอก (Goodfella)', artists: ['polycat'] },
  'friday on the high way': { canonical: 'ซิ่ง (Friday On The High Way)', artists: ['polycat'] },
  'fridayonthehighway': { canonical: 'ซิ่ง (Friday On The High Way)', artists: ['polycat'] },
  'ซิ่ง': { canonical: 'ซิ่ง (Friday On The High Way)', artists: ['polycat'] },
  'pistol': { canonical: 'ปืน (Pistol)', artists: ['polycat'] },
  'ปืน': { canonical: 'ปืน (Pistol)', artists: ['polycat'] },
  'you had me at hello': { canonical: 'เวลาเธอยิ้ม (You Had Me At Hello)', artists: ['polycat'] },
  'youhadmeathello': { canonical: 'เวลาเธอยิ้ม (You Had Me At Hello)', artists: ['polycat'] },
  'เวลาเธอยิ้ม': { canonical: 'เวลาเธอยิ้ม (You Had Me At Hello)', artists: ['polycat'] },
  'alright': { canonical: 'มันเป็นใคร (Alright)', artists: ['polycat'] },
  'มันเป็นใคร': { canonical: 'มันเป็นใคร (Alright)', artists: ['polycat'] },
  'so long': { canonical: 'พบกันใหม่ (So Long)', artists: ['polycat'] },
  'solong': { canonical: 'พบกันใหม่ (So Long)', artists: ['polycat'] },
  'พบกันใหม่': { canonical: 'พบกันใหม่ (So Long)', artists: ['polycat'] },
  'teardrops': { canonical: 'เป็นเพราะฝน (Teardrops)', artists: ['polycat'] },
  'เป็นเพราะฝน': { canonical: 'เป็นเพราะฝน (Teardrops)', artists: ['polycat'] },

  // BOWKYLION
  'lionheart': { canonical: 'เจ้าป่า (Lionheart)', artists: ['bowkylion'] },
  'เจ้าป่า': { canonical: 'เจ้าป่า (Lionheart)', artists: ['bowkylion'] },
  'your ex': { canonical: 'ค.ควาย (Your Ex)', artists: ['bowkylion'] },
  'yourex': { canonical: 'ค.ควาย (Your Ex)', artists: ['bowkylion'] },
  'ค.ควาย': { canonical: 'ค.ควาย (Your Ex)', artists: ['bowkylion'] },
  'ค ควาย': { canonical: 'ค.ควาย (Your Ex)', artists: ['bowkylion'] },
  'so what': { canonical: 'คือราย (so what)', artists: ['bowkylion'] },
  'sowhat': { canonical: 'คือราย (so what)', artists: ['bowkylion'] },
  'คือราย': { canonical: 'คือราย (so what)', artists: ['bowkylion'] },
  'your arm': { canonical: 'แขนซ้าย (Your Arm)', artists: ['bowkylion'] },
  'yourarm': { canonical: 'แขนซ้าย (Your Arm)', artists: ['bowkylion'] },
  'แขนซ้าย': { canonical: 'แขนซ้าย (Your Arm)', artists: ['bowkylion'] },
  'untold': { canonical: 'คิดถึงแต่ (Untold)', artists: ['bowkylion'] },
  'คิดถึงแต่': { canonical: 'คิดถึงแต่ (Untold)', artists: ['bowkylion'] },
  'crush': { canonical: 'ยิ้มมา (Crush)', artists: ['bowkylion'] },
  'ยิ้มมา': { canonical: 'ยิ้มมา (Crush)', artists: ['bowkylion'] },
  'awesome love': { canonical: 'รักไปร้องไห้ไป (Awesome Love)', artists: ['bowkylion'] },
  'awesomelove': { canonical: 'รักไปร้องไห้ไป (Awesome Love)', artists: ['bowkylion'] },
  'รักไปร้องไห้ไป': { canonical: 'รักไปร้องไห้ไป (Awesome Love)', artists: ['bowkylion'] },
  '1st': { canonical: 'ก่อนใคร (1st)', artists: ['bowkylion'] },
  'ก่อนใคร': { canonical: 'ก่อนใคร (1st)', artists: ['bowkylion'] },
  'afternoon': { canonical: 'ทิวาสวัสดิ์ (Afternoon)', artists: ['bowkylion'] },
  'ทิวาสวัสดิ์': { canonical: 'ทิวาสวัสดิ์ (Afternoon)', artists: ['bowkylion'] },
  'best wishes': { canonical: 'บานปลาย (best wishes)', artists: ['bowkylion'] },
  'bestwishes': { canonical: 'บานปลาย (best wishes)', artists: ['bowkylion'] },
  'บานปลาย': { canonical: 'บานปลาย (best wishes)', artists: ['bowkylion'] },
  'recall': { canonical: 'วาดไว้ (recall)', artists: ['bowkylion'] },
  'วาดไว้': { canonical: 'วาดไว้ (recall)', artists: ['bowkylion'] },
  'attention': { canonical: 'ทราบแล้วเปลี่ยน (attention)', artists: ['bowkylion'] },
  'ทราบแล้วเปลี่ยน': { canonical: 'ทราบแล้วเปลี่ยน (attention)', artists: ['bowkylion'] },
  'post-it': { canonical: 'รู้กันแค่นี้ (post-it)', artists: ['bowkylion'] },
  'postit': { canonical: 'รู้กันแค่นี้ (post-it)', artists: ['bowkylion'] },
  'รู้กันแค่นี้': { canonical: 'รู้กันแค่นี้ (post-it)', artists: ['bowkylion'] },
  'fever': { canonical: 'เลี้ยงไข้ (fever)', artists: ['bowkylion'] },
  'เลี้ยงไข้': { canonical: 'เลี้ยงไข้ (fever)', artists: ['bowkylion'] },

  // NONT TANONT
  'unniversary': { canonical: 'วันครบเลิก (UNNIVERSARY)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'วันครบเลิก': { canonical: 'วันครบเลิก (UNNIVERSARY)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'it\'s ok': { canonical: 'ไม่เป็นไรที่รัก (It\'s ok)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'its ok': { canonical: 'ไม่เป็นไรที่รัก (It\'s ok)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'itsok': { canonical: 'ไม่เป็นไรที่รัก (It\'s ok)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'ไม่เป็นไรที่รัก': { canonical: 'ไม่เป็นไรที่รัก (It\'s ok)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'bandage': { canonical: 'ผ้าพันแผล (Bandage)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'ผ้าพันแผล': { canonical: 'ผ้าพันแผล (Bandage)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'melt': { canonical: 'โต๊ะริม (melt)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'โต๊ะริม': { canonical: 'โต๊ะริม (melt)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'i don\'t mind': { canonical: 'แค่แอบหวัง (I Don\'t Mind)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'i dont mind': { canonical: 'แค่แอบหวัง (I Don\'t Mind)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'idontmind': { canonical: 'แค่แอบหวัง (I Don\'t Mind)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'แค่แอบหวัง': { canonical: 'แค่แอบหวัง (I Don\'t Mind)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'let me love you': { canonical: 'ถ้าเธอไม่อยากโชคร้ายเรื่องความรัก (Let Me Love You)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'letmeloveyou': { canonical: 'ถ้าเธอไม่อยากโชคร้ายเรื่องความรัก (Let Me Love You)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'ถ้าเธอไม่อยากโชคร้ายเรื่องความรัก': { canonical: 'ถ้าเธอไม่อยากโชคร้ายเรื่องความรัก (Let Me Love You)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'ain\'t no other one': { canonical: 'เธอมีคนเดียวบนโลก (AIN\'T NO OTHER ONE)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'aint no other one': { canonical: 'เธอมีคนเดียวบนโลก (AIN\'T NO OTHER ONE)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'aintnootherone': { canonical: 'เธอมีคนเดียวบนโลก (AIN\'T NO OTHER ONE)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'เธอมีคนเดียวบนโลก': { canonical: 'เธอมีคนเดียวบนโลก (AIN\'T NO OTHER ONE)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'new me': { canonical: 'คนใหม่ (New Me)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'newme': { canonical: 'คนใหม่ (New Me)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'คนใหม่': { canonical: 'คนใหม่ (New Me)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'always with me': { canonical: 'ทุกนาทีที่สวยงาม (Always With Me)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'alwayswithme': { canonical: 'ทุกนาทีที่สวยงาม (Always With Me)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'ทุกนาทีที่สวยงาม': { canonical: 'ทุกนาทีที่สวยงาม (Always With Me)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'lean on': { canonical: 'พิง (Lean On)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'leanon': { canonical: 'พิง (Lean On)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'พิง': { canonical: 'พิง (Lean On)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'are you sure': { canonical: 'แน่ใจไหม (Are You Sure?)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'are you sure?': { canonical: 'แน่ใจไหม (Are You Sure?)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'areyousure': { canonical: 'แน่ใจไหม (Are You Sure?)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'แน่ใจไหม': { canonical: 'แน่ใจไหม (Are You Sure?)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'white flag': { canonical: 'จำนน (White Flag)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'whiteflag': { canonical: 'จำนน (White Flag)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'จำนน': { canonical: 'จำนน (White Flag)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'crazy': { canonical: 'คลั่งรัก (Crazy)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },
  'คลั่งรัก': { canonical: 'คลั่งรัก (Crazy)', artists: ['nont tanont', 'นนท์ ธนนท์', 'nont'] },

  // SERIOUS BACON (additional)
  'best friend 4ever': { canonical: 'เพื่อนดีเด่น (BEST FRIEND 4EVER)', artists: ['serious bacon'] },
  'bestfriend4ever': { canonical: 'เพื่อนดีเด่น (BEST FRIEND 4EVER)', artists: ['serious bacon'] },
  'เพื่อนดีเด่น': { canonical: 'เพื่อนดีเด่น (BEST FRIEND 4EVER)', artists: ['serious bacon'] },
  'can you stay': { canonical: 'แป๊บนึง (Can You Stay?)', artists: ['serious bacon'] },
  'can you stay?': { canonical: 'แป๊บนึง (Can You Stay?)', artists: ['serious bacon'] },
  'canyoustay': { canonical: 'แป๊บนึง (Can You Stay?)', artists: ['serious bacon'] },
  'แป๊บนึง': { canonical: 'แป๊บนึง (Can You Stay?)', artists: ['serious bacon'] },
  'promise me': { canonical: 'รักเขาแทนฉันที (Promise Me)', artists: ['serious bacon'] },
  'promiseme': { canonical: 'รักเขาแทนฉันที (Promise Me)', artists: ['serious bacon'] },
  'รักเขาแทนฉันที': { canonical: 'รักเขาแทนฉันที (Promise Me)', artists: ['serious bacon'] },

  // PURPEECH (additional)
  'sincare': { canonical: 'หากจะเพียงขอ (Sincare)', artists: ['purpeech'] },
  'หากจะเพียงขอ': { canonical: 'หากจะเพียงขอ (Sincare)', artists: ['purpeech'] },
  'consoled': { canonical: 'ทิ้งไว้อย่างพอใจ (Consoled)', artists: ['purpeech'] },
  'ทิ้งไว้อย่างพอใจ': { canonical: 'ทิ้งไว้อย่างพอใจ (Consoled)', artists: ['purpeech'] },
  '1920': { canonical: 'ภาพถ่ายวันวาน (1920)', artists: ['purpeech'] },
  'ภาพถ่ายวันวาน': { canonical: 'ภาพถ่ายวันวาน (1920)', artists: ['purpeech'] },
  'parsec': { canonical: 'กาลครั้งหนึ่งบนโลก (Parsec)', artists: ['purpeech'] },
  'กาลครั้งหนึ่งบนโลก': { canonical: 'กาลครั้งหนึ่งบนโลก (Parsec)', artists: ['purpeech'] },
  '.png': { canonical: 'บังเอิญพบทานตะวัน (.png)', artists: ['purpeech'] },
  'png': { canonical: 'บังเอิญพบทานตะวัน (.png)', artists: ['purpeech'] },
  'บังเอิญพบทานตะวัน': { canonical: 'บังเอิญพบทานตะวัน (.png)', artists: ['purpeech'] },

  // Mirrr (additional)
  'firework': { canonical: 'ดอกไม้ไฟ (Firework)', artists: ['mirrr'] },
  'ดอกไม้ไฟ': { canonical: 'ดอกไม้ไฟ (Firework)', artists: ['mirrr'] },
  'keep it low key': { canonical: 'ไม่รู้ดิ (Keep It Low Key)', artists: ['mirrr'] },
  'keepitlowkey': { canonical: 'ไม่รู้ดิ (Keep It Low Key)', artists: ['mirrr'] },
  'ไม่รู้ดิ': { canonical: 'ไม่รู้ดิ (Keep It Low Key)', artists: ['mirrr'] },
  'my favorite': { canonical: 'เจ้าของที่ (My Favorite)', artists: ['mirrr'] },
  'myfavorite': { canonical: 'เจ้าของที่ (My Favorite)', artists: ['mirrr'] },
  'เจ้าของที่': { canonical: 'เจ้าของที่ (My Favorite)', artists: ['mirrr'] },
  'loop': { canonical: 'กลับมาที่เดิม (Loop)', artists: ['mirrr'] },
  'กลับมาที่เดิม': { canonical: 'กลับมาที่เดิม (Loop)', artists: ['mirrr'] },
  'ex': { canonical: 'เธอเองจะรู้บ้างไหม (Ex)', artists: ['mirrr'] },
  'เธอเองจะรู้บ้างไหม': { canonical: 'เธอเองจะรู้บ้างไหม (Ex)', artists: ['mirrr'] },
  'ninja': { canonical: 'นินจา (Ninja)', artists: ['mirrr'] },
  'นินจา': { canonical: 'นินจา (Ninja)', artists: ['mirrr'] },
  'ghost': { canonical: 'ไม่ไปไหน (Ghost)', artists: ['mirrr'] },
  'ไม่ไปไหน': { canonical: 'ไม่ไปไหน (Ghost)', artists: ['mirrr'] },
  'no forever': { canonical: 'ตลอดไปไม่มีจริง (NO FOREVER)', artists: ['mirrr'] },
  'no!forever?': { canonical: 'ตลอดไปไม่มีจริง (NO FOREVER)', artists: ['mirrr'] },
  'noforever': { canonical: 'ตลอดไปไม่มีจริง (NO FOREVER)', artists: ['mirrr'] },
  'ตลอดไปไม่มีจริง': { canonical: 'ตลอดไปไม่มีจริง (NO FOREVER)', artists: ['mirrr'] },
  'cameo': { canonical: 'ชาตินี้พอ (Cameo)', artists: ['mirrr'] },
  'ชาตินี้พอ': { canonical: 'ชาตินี้พอ (Cameo)', artists: ['mirrr'] },
  'heartwall': { canonical: 'กำแพงหัวใจ (Heartwall)', artists: ['mirrr'] },
  'กำแพงหัวใจ': { canonical: 'กำแพงหัวใจ (Heartwall)', artists: ['mirrr'] },
  'gentle hug': { canonical: 'กอดความเจ็บปวด (Gentle Hug)', artists: ['mirrr'] },
  'gentlehug': { canonical: 'กอดความเจ็บปวด (Gentle Hug)', artists: ['mirrr'] },
  'กอดความเจ็บปวด': { canonical: 'กอดความเจ็บปวด (Gentle Hug)', artists: ['mirrr'] },
  'nicotine': { canonical: 'นิโคติน (Nicotine)', artists: ['mirrr'] },
  'นิโคติน': { canonical: 'นิโคติน (Nicotine)', artists: ['mirrr'] },

  // Dept (additional)
  'all in': { canonical: 'หมดนี้ให้เธอ (All In)', artists: ['dept'] },
  'allin': { canonical: 'หมดนี้ให้เธอ (All In)', artists: ['dept'] },
  'หมดนี้ให้เธอ': { canonical: 'หมดนี้ให้เธอ (All In)', artists: ['dept'] },
  'my vanilla': { canonical: 'เพราะเธอนั้นเป็นเหมือนดั่งโลกทั้งใบ (My Vanilla)', artists: ['dept'] },
  'myvanilla': { canonical: 'เพราะเธอนั้นเป็นเหมือนดั่งโลกทั้งใบ (My Vanilla)', artists: ['dept'] },
  'เพราะเธอนั้นเป็นเหมือนดั่งโลกทั้งใบ': { canonical: 'เพราะเธอนั้นเป็นเหมือนดั่งโลกทั้งใบ (My Vanilla)', artists: ['dept'] },
  'somewhere': { canonical: 'แค่วันพรุ่งนี้ที่ไม่มีเรา (Somewhere)', artists: ['dept'] },
  'แค่วันพรุ่งนี้ที่ไม่มีเรา': { canonical: 'แค่วันพรุ่งนี้ที่ไม่มีเรา (Somewhere)', artists: ['dept'] },
  'cycle of love': { canonical: 'ฤดู (Cycle of Love)', artists: ['dept'] },
  'cycleoflove': { canonical: 'ฤดู (Cycle of Love)', artists: ['dept'] },
  'ฤดู': { canonical: 'ฤดู (Cycle of Love)', artists: ['dept'] },
  'farewell': { canonical: 'คงต้องบอกลาแล้ว (Farewell)', artists: ['dept'] },
  'คงต้องบอกลาแล้ว': { canonical: 'คงต้องบอกลาแล้ว (Farewell)', artists: ['dept'] },
  'cola': { canonical: 'หยุดสักที (Cola)', artists: ['dept'] },
  'หยุดสักที': { canonical: 'หยุดสักที (Cola)', artists: ['dept'] },

  // Loserpop (additional)
  'fall': { canonical: 'ดาวตก (fall)', artists: ['loserpop'] },
  'ดาวตก': { canonical: 'ดาวตก (fall)', artists: ['loserpop'] },
  'love you already': { canonical: 'ฉันรักเธอแล้ว (love you already)', artists: ['loserpop'] },
  'loveyoualready': { canonical: 'ฉันรักเธอแล้ว (love you already)', artists: ['loserpop'] },
  'ฉันรักเธอแล้ว': { canonical: 'ฉันรักเธอแล้ว (love you already)', artists: ['loserpop'] },
  'butterscotch': { canonical: 'ทางที่ดี (butterscotch)', artists: ['loserpop'] },
  'ทางที่ดี': { canonical: 'ทางที่ดี (butterscotch)', artists: ['loserpop'] },
  'turn around': { canonical: 'กลับไปกลับมา (turn around)', artists: ['loserpop'] },
  'turnaround': { canonical: 'กลับไปกลับมา (turn around)', artists: ['loserpop'] },
  'กลับไปกลับมา': { canonical: 'กลับไปกลับมา (turn around)', artists: ['loserpop'] },
  'strangers': { canonical: 'เคย (strangers)', artists: ['loserpop'] },
  'เคย': { canonical: 'เคย (strangers)', artists: ['loserpop'] },

  // Landokmai
  'echo': { canonical: 'เมื่อไหร่ที่คิดถึงเธอ (Echo)', artists: ['landokmai'] },
  'เมื่อไหร่ที่คิดถึงเธอ': { canonical: 'เมื่อไหร่ที่คิดถึงเธอ (Echo)', artists: ['landokmai'] },
  'still': { canonical: 'เกาะลอยฟ้า (Still)', artists: ['landokmai'] },
  'เกาะลอยฟ้า': { canonical: 'เกาะลอยฟ้า (Still)', artists: ['landokmai'] },
  'white flag': { canonical: 'ยอม (White Flag)', artists: ['landokmai'] },
  'ยอม': { canonical: 'ยอม (White Flag)', artists: ['landokmai'] },
  'drizzle': { canonical: 'ฤดูฝัน (Drizzle)', artists: ['landokmai'] },
  'ฤดูฝัน': { canonical: 'ฤดูฝัน (Drizzle)', artists: ['landokmai'] },
  'blooming': { canonical: 'เพลงรักเพลงแรก (Blooming)', artists: ['landokmai'] },
  'เพลงรักเพลงแรก': { canonical: 'เพลงรักเพลงแรก (Blooming)', artists: ['landokmai'] },
  'nomad\'s lullaby': { canonical: 'ในวันพรุ่งนี้ขอให้เป็นวันที่ดี (Nomad\'s Lullaby)', artists: ['landokmai'] },
  'nomads lullaby': { canonical: 'ในวันพรุ่งนี้ขอให้เป็นวันที่ดี (Nomad\'s Lullaby)', artists: ['landokmai'] },
  'ในวันพรุ่งนี้ขอให้เป็นวันที่ดี': { canonical: 'ในวันพรุ่งนี้ขอให้เป็นวันที่ดี (Nomad\'s Lullaby)', artists: ['landokmai'] },
  'please be true': { canonical: 'ด้วยใจยินดี (Please be true)', artists: ['landokmai'] },
  'pleasebetrue': { canonical: 'ด้วยใจยินดี (Please be true)', artists: ['landokmai'] },
  'ด้วยใจยินดี': { canonical: 'ด้วยใจยินดี (Please be true)', artists: ['landokmai'] },
  'our sunset': { canonical: 'ฟ้า (Our Sunset)', artists: ['landokmai'] },
  'oursunset': { canonical: 'ฟ้า (Our Sunset)', artists: ['landokmai'] },

  // Sqweez Animal
  'half an eyesight': { canonical: 'ครึ่งสายตา (Half an Eyesight)', artists: ['sqweez animal'] },
  'halfaneyesight': { canonical: 'ครึ่งสายตา (Half an Eyesight)', artists: ['sqweez animal'] },
  'ครึ่งสายตา': { canonical: 'ครึ่งสายตา (Half an Eyesight)', artists: ['sqweez animal'] },
  'undeniable': { canonical: 'จะรักดีไหม (Undeniable)', artists: ['sqweez animal'] },
  'จะรักดีไหม': { canonical: 'จะรักดีไหม (Undeniable)', artists: ['sqweez animal'] },
  'i\'m not lonely': { canonical: 'ฉันไม่เหงา (I\'m Not Lonely)', artists: ['sqweez animal'] },
  'im not lonely': { canonical: 'ฉันไม่เหงา (I\'m Not Lonely)', artists: ['sqweez animal'] },
  'ฉันไม่เหงา': { canonical: 'ฉันไม่เหงา (I\'m Not Lonely)', artists: ['sqweez animal'] },
  'love never lie': { canonical: 'รักไม่หลอก (Love Never Lie)', artists: ['sqweez animal'] },
  'loveneverlie': { canonical: 'รักไม่หลอก (Love Never Lie)', artists: ['sqweez animal'] },
  'รักไม่หลอก': { canonical: 'รักไม่หลอก (Love Never Lie)', artists: ['sqweez animal'] },
  'not looking back': { canonical: 'ไม่มองกลับหลัง (Not Looking Back)', artists: ['sqweez animal'] },
  'notlookingback': { canonical: 'ไม่มองกลับหลัง (Not Looking Back)', artists: ['sqweez animal'] },
  'ไม่มองกลับหลัง': { canonical: 'ไม่มองกลับหลัง (Not Looking Back)', artists: ['sqweez animal'] },
  'another day': { canonical: 'อีกสักครั้ง (Another Day)', artists: ['sqweez animal'] },
  'anotherday': { canonical: 'อีกสักครั้ง (Another Day)', artists: ['sqweez animal'] },
  'อีกสักครั้ง': { canonical: 'อีกสักครั้ง (Another Day)', artists: ['sqweez animal'] },
  'it ain\'t too late': { canonical: 'อาจยังไม่สาย (It Ain\'t Too Late)', artists: ['sqweez animal'] },
  'it aint too late': { canonical: 'อาจยังไม่สาย (It Ain\'t Too Late)', artists: ['sqweez animal'] },
  'อาจยังไม่สาย': { canonical: 'อาจยังไม่สาย (It Ain\'t Too Late)', artists: ['sqweez animal'] },
  'restart': { canonical: 'เริ่มใหม่ (Restart)', artists: ['sqweez animal'] },
  'เริ่มใหม่': { canonical: 'เริ่มใหม่ (Restart)', artists: ['sqweez animal'] },
  'shy': { canonical: 'อาย (Shy)', artists: ['sqweez animal'] },
  'อาย': { canonical: 'อาย (Shy)', artists: ['sqweez animal'] },

  // Moderndog
  'today, last year': { canonical: 'วันนี้เมื่อปีก่อน (Today, Last Year)', artists: ['moderndog'] },
  'today last year': { canonical: 'วันนี้เมื่อปีก่อน (Today, Last Year)', artists: ['moderndog'] },
  'todaylastyear': { canonical: 'วันนี้เมื่อปีก่อน (Today, Last Year)', artists: ['moderndog'] },
  'วันนี้เมื่อปีก่อน': { canonical: 'วันนี้เมื่อปีก่อน (Today, Last Year)', artists: ['moderndog'] },

  // Labanoon
  'delivery': { canonical: 'เดลิเวอรี่ (Delivery)', artists: ['labanoon'] },
  'เดลิเวอรี่': { canonical: 'เดลิเวอรี่ (Delivery)', artists: ['labanoon'] }
};

console.log('Total new rules:', Object.keys(NEW_RULES).length);
