export const THAI_SONG_TRANSLATION_RULES: Record<string, ThaiSongTranslationRule | ThaiSongTranslationRule[]> = {
  ".png": { canonical: "บังเอิญพบทานตะวัน (.png)", artists: ["purpeech"] },
  "1001": { canonical: "1001 (You're Lovely)", artists: ["serious bacon"] },
  "1001 youre lovely": { canonical: "1001 (You're Lovely)", artists: ["serious bacon"] },
  "17 mins": { canonical: "17 นาที (17 Mins)", artists: ["milli"] },
  "17 นาที": { canonical: "17 นาที (17 Mins)", artists: ["milli"] },
  "1920": { canonical: "ภาพถ่ายวันวาน (1920)", artists: ["purpeech"] },
  "1st": { canonical: "ก่อนใคร (1st)", artists: ["bowkylion"] },
  "2cool2care": { canonical: "โดนเทแต่เท่อยู่ (2cool2care)", artists: ["bamm"] },
  "365 nichi no kamihikouki": { canonical: "365 วันกับเครื่องบินกระดาษ (365 Nichi no Kamihikouki)", artists: ["bnk48","akb48"] },
  "365nichinokamihikouki": { canonical: "365 วันกับเครื่องบินกระดาษ (365 Nichi no Kamihikouki)", artists: ["bnk48","akb48"] },
  "a beautiful ride": { canonical: "การเดินทางที่สวยงาม (A Beautiful Ride)", artists: ["billkin"] },
  "abeautifulride": { canonical: "การเดินทางที่สวยงาม (A Beautiful Ride)", artists: ["billkin"] },
  "across the worlds": { canonical: "เหวี่ยง (Across The Worlds)", artists: ["safeplanet"] },
  "acrosstheworlds": { canonical: "เหวี่ยง (Across The Worlds)", artists: ["safeplanet"] },
  "adore": { canonical: "หินหยดลงน้ำ (Adore)" },
  "afternoon": { canonical: "ทิวาสวัสดิ์ (Afternoon)", artists: ["bowkylion"] },
  "ain't no other one": { canonical: "เธอมีคนเดียวบนโลก (AIN'T NO OTHER ONE)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "aint no other one": { canonical: "เธอมีคนเดียวบนโลก (AIN'T NO OTHER ONE)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "aintnootherone": { canonical: "เธอมีคนเดียวบนโลก (AIN'T NO OTHER ONE)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "aitakatta": { canonical: "อยากจะได้พบเธอ (Aitakatta)", artists: ["bnk48","akb48"] },
  "all in": { canonical: "หมดนี้ให้เธอ (All In)", artists: ["dept"] },
  "allin": { canonical: "หมดนี้ให้เธอ (All In)", artists: ["dept"] },
  "alright": [{ canonical: "สบายดี (Alright)", artists: ["purpeech"] }, { canonical: "มันเป็นใคร (Alright)", artists: ["polycat"] }],
  "always": { canonical: "เพียงเธอ (Always)", artists: ["safeplanet"] },
  "always with me": { canonical: "ทุกนาทีที่สวยงาม (Always With Me)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "alwayswithme": { canonical: "ทุกนาทีที่สวยงาม (Always With Me)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "another day": { canonical: "อีกสักครั้ง (Another Day)", artists: ["sqweez animal"] },
  "anotherday": { canonical: "อีกสักครั้ง (Another Day)", artists: ["sqweez animal"] },
  "anything": { canonical: "หมอนอิง (Anything)", artists: ["nunew","นุนิว"] },
  "are you sure": { canonical: "แน่ใจไหม (Are You Sure?)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "are you sure?": { canonical: "แน่ใจไหม (Are You Sure?)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "areyousure": { canonical: "แน่ใจไหม (Are You Sure?)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "attention": { canonical: "ทราบแล้วเปลี่ยน (attention)", artists: ["bowkylion"] },
  "awesome love": { canonical: "รักไปร้องไห้ไป (Awesome Love)", artists: ["bowkylion"] },
  "awesomelove": { canonical: "รักไปร้องไห้ไป (Awesome Love)", artists: ["bowkylion"] },
  "ba ra mee hang wang nam yen": { canonical: "บารมีแห่งวังน้ำเย็น", artists: ["ก้อง ห้วยไร่"] },
  "back to you": { canonical: "แน่ใจไหม (Back To You)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "bad boy": { canonical: "ทรงอย่างแบด (Bad Boy)", artists: ["paper planes"] },
  "badboy": { canonical: "ทรงอย่างแบด (Bad Boy)", artists: ["paper planes"] },
  "baggage": { canonical: "เดอะแบก (Baggage)", artists: ["tilly birds"] },
  "bammboo": { canonical: "เธอเก่งที่สุดแล้ว (bammBOO)", artists: ["bamm"] },
  "bandage": { canonical: "ผ้าพันแผล (Bandage)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "bangkok winter": { canonical: "ฤดูหนาว (Bangkok Winter)", artists: ["tilly birds","paam"] },
  "bangkokwinter": { canonical: "ฤดูหนาว (Bangkok Winter)", artists: ["tilly birds","paam"] },
  "because of you i shine": { canonical: "เพราะเธอคือเพลงโปรด (Because of You, I Shine)" },
  "because of you, i shine": { canonical: "เพราะเธอคือเพลงโปรด (Because of You, I Shine)" },
  "best friend 4ever": { canonical: "เพื่อนดีเด่น (BEST FRIEND 4EVER)", artists: ["serious bacon"] },
  "best luck": { canonical: "ไม่เปลี่ยนเลย (Best Luck)", artists: ["fellow fellow","fellowfellow"] },
  "best wishes": { canonical: "บานปลาย (Best Wishes)", artists: ["bowkylion"] },
  "bestfriend4ever": { canonical: "เพื่อนดีเด่น (BEST FRIEND 4EVER)", artists: ["serious bacon"] },
  "bestluck": { canonical: "ไม่เปลี่ยนเลย (Best Luck)", artists: ["fellow fellow","fellowfellow"] },
  "bestwishes": { canonical: "บานปลาย (best wishes)", artists: ["bowkylion"] },
  "blooming": { canonical: "เพลงรักเพลงแรก (Blooming)", artists: ["landokmai"] },
  "blur": { canonical: "สถานะเบลอ (Blurrr)", artists: ["proxie"] },
  "blurrr": { canonical: "สถานะเบลอ (Blurrr)", artists: ["proxie"] },
  "bnk festival": { canonical: "บีเอ็นเคเฟสติวัล (BNK Festival)", artists: ["bnk48"] },
  "boo": { canonical: "งอนละ (Boo)", artists: ["pixxie"] },
  "brother zone": { canonical: "แค่น้องชาย (brother zone)", artists: ["bus"] },
  "brotherzone": { canonical: "แค่น้องชาย (brother zone)", artists: ["bus"] },
  "bubble": { canonical: "โลกอีกใบ (Bubble)", artists: ["zom marie","ส้ม มารี"] },
  "butterscotch": { canonical: "ทางที่ดี (butterscotch)", artists: ["loserpop"] },
  "c.i.a. (khon chai)": { canonical: "C.I.A. (ค้นใจ)", artists: ["d2b"] },
  "call me": { canonical: "ไม่อยากเหงาแล้ว (Call Me)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "callme": { canonical: "ไม่อยากเหงาแล้ว (Call Me)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "cameo": { canonical: "ชาตินี้พอ (Cameo)", artists: ["mirrr"] },
  "can you stay": { canonical: "แป๊บนึง (Can You Stay?)", artists: ["serious bacon"] },
  "can you stay?": { canonical: "แป๊บนึง (Can You Stay?)", artists: ["serious bacon"] },
  "can't help it": { canonical: "ช่วยไม่ได้ (Can't Help It)", artists: ["urboytj","urboy"] },
  "can't keep up": { canonical: "ลู่วิ่ง (Can't Keep Up)", artists: ["tilly birds"] },
  "can't translate": { canonical: "แปลไม่ออก (Can't Translate)", artists: ["billkin"] },
  "cant help it": { canonical: "ช่วยไม่ได้ (Can't Help It)", artists: ["urboytj","urboy"] },
  "cant keep up": { canonical: "ลู่วิ่ง (Can't Keep Up)", artists: ["tilly birds"] },
  "cant translate": { canonical: "แปลไม่ออก (Can't Translate)", artists: ["billkin"] },
  "cantkeepup": { canonical: "ลู่วิ่ง (Can't Keep Up)", artists: ["tilly birds"] },
  "canttranslate": { canonical: "แปลไม่ออก (Can't Translate)", artists: ["billkin"] },
  "canyoustay": { canonical: "แป๊บนึง (Can You Stay?)", artists: ["serious bacon"] },
  "choose me": { canonical: "เลือกคนที่เขารักเรา (Choose Me)", artists: ["three man down"] },
  "cia khon chai": { canonical: "C.I.A. (ค้นใจ)", artists: ["d2b"] },
  "ciakhonchai": { canonical: "C.I.A. (ค้นใจ)", artists: ["d2b"] },
  "cinderella": { canonical: "ซินเดอเรลล่า (Cinderella)", artists: ["tattoo colour"] },
  "city": { canonical: "ข้างกัน (City)", artists: ["three man down","telex telexs"] },
  "close": { canonical: "คนใหม่เขาดูแลอยู่ (Close)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "close enough": { canonical: "เกือบเป็นแฟน (Close Enough)", artists: ["bamm"] },
  "close friend": { canonical: "เพื่อนกันไม่เลิกกัน (Close Friend)", artists: ["bamm"] },
  "closeenough": { canonical: "เกือบเป็นแฟน (Close Enough)", artists: ["bamm"] },
  "closefriend": { canonical: "เพื่อนกันไม่เลิกกัน (Close Friend)", artists: ["bamm"] },
  "cola": { canonical: "หยุดสักที (Cola)", artists: ["dept"] },
  "cold fire": { canonical: "ไฟเย็น (Cold Fire)", artists: ["youngohm"] },
  "coldfire": { canonical: "ไฟเย็น (Cold Fire)", artists: ["youngohm"] },
  "coming of age": { canonical: "ไม่ปล่อยมือ (Coming of Age)", artists: ["billkin","pp krit","pp"] },
  "comingofage": { canonical: "ไม่ปล่อยมือ (Coming of Age)", artists: ["billkin","pp krit","pp"] },
  "consoled": { canonical: "ทิ้งไว้อย่างพอใจ (Consoled)", artists: ["purpeech"] },
  "crazy": { canonical: "คลั่งรัก (Crazy)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "crazy love": { canonical: "รักบ้าบอ (Crazy Love)", artists: ["proxie"] },
  "crazylove": { canonical: "รักบ้าบอ (Crazy Love)", artists: ["proxie"] },
  "crush": { canonical: "ยิ้มมา (Crush)", artists: ["bowkylion"] },
  "curse": { canonical: "ฉันจะฉาปเธอ (Curse)", artists: ["bamm"] },
  "cut me off": { canonical: "อย่าพี่น้อง (Cut Me Off)", artists: ["tilly birds"] },
  "cutmeoff": { canonical: "อย่าพี่น้อง (Cut Me Off)", artists: ["tilly birds"] },
  "cycle of love": { canonical: "ฤดู (Cycle of Love)", artists: ["dept"] },
  "cycleoflove": { canonical: "ฤดู (Cycle of Love)", artists: ["dept"] },
  "dear friend": { canonical: "เพื่อนรัก (Dear Friend)", artists: ["the parkinson","parkinson"] },
  "ded": { canonical: "เด็ด (DED)", artists: ["pixxie"] },
  "delivery": { canonical: "เดลิเวอรี่ (Delivery)", artists: ["labanoon"] },
  "dna": { canonical: "ดีเอ็นเอ (D.N.A)", artists: ["bnk48"] },
  "do it without me": { canonical: "ส่วนต่าง (Do It Without Me)" },
  "do you mind": { canonical: "รังเกียจกันไหม (Do You Mind)" },
  "do you mind?": { canonical: "รังเกียจกันไหม (Do You Mind)" },
  "doyoumind": { canonical: "รังเกียจกันไหม (Do You Mind)" },
  "drizzle": { canonical: "ฤดูฝัน (Drizzle)", artists: ["landokmai"] },
  "echo": { canonical: "เมื่อไหร่ที่คิดถึงเธอ (Echo)", artists: ["landokmai"] },
  "eek krang": { canonical: "อีกครั้ง", artists: ["getsunova"] },
  "everyday": { canonical: "ทุกวัน (Everyday)", artists: ["scrubb"] },
  "ex": { canonical: "เธอเองจะรู้บ้างไหม (Ex)", artists: ["mirrr"] },
  "exceptional": { canonical: "ข้อยกเว้น (Exceptional)", artists: ["4eve"] },
  "expert": { canonical: "เก่งแต่เรื่องคนอื่น (Expert)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "extraordinary": { canonical: "ธรรมดาแสนพิเศษ (Extraordinary)" },
  "eyes don't lie": { canonical: "สายตาหลอกกันไม่ได้ (Eyes Don't Lie)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "eyes dont lie": { canonical: "สายตาหลอกกันไม่ได้ (Eyes Don't Lie)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "eyesdontlie": { canonical: "สายตาหลอกกันไม่ได้ (Eyes Don't Lie)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "fade": { canonical: "ลืมไปแล้วว่าลืมยังไง (Fade)", artists: ["jeff satur","เจฟ ซาเตอร์"] },
  "faith": { canonical: "ภักดี (Faith)", artists: ["polycat"] },
  "fall": { canonical: "ดาวตก (fall)", artists: ["loserpop"] },
  "farewell": { canonical: "คงต้องบอกลาแล้ว (Farewell)", artists: ["dept"] },
  "fever": { canonical: "เลี้ยงไข้ (fever)", artists: ["bowkylion"] },
  "firework": { canonical: "ดอกไม้ไฟ (Firework)", artists: ["mirrr"] },
  "first love": { canonical: "รักแรก (First Love)" },
  "first rabbit": { canonical: "กระต่ายตัวแรก (First Rabbit)", artists: ["bnk48"] },
  "firstlove": { canonical: "รักแรก (First Love)" },
  "forever mate": { canonical: "เพื่อนไม่จริง (Forever Mate)", artists: ["polycat"] },
  "forevermate": { canonical: "เพื่อนไม่จริง (Forever Mate)", artists: ["polycat"] },
  "friday on the high way": { canonical: "ซิ่ง (Friday On The High Way)", artists: ["polycat"] },
  "fridayonthehighway": { canonical: "ซิ่ง (Friday On The High Way)", artists: ["polycat"] },
  "friend zone": { canonical: "เพื่อนชุบแป้งทอด (Friend Zone)", artists: ["three man down"] },
  "fung jum jom": { canonical: "ฝัง จำ จม (Fung Jum Jom)", artists: ["silly fools"] },
  "fungjumjom": { canonical: "ฝัง จำ จม (Fung Jum Jom)", artists: ["silly fools"] },
  "gentle hug": { canonical: "กอดความเจ็บปวด (Gentle Hug)", artists: ["mirrr"] },
  "gentlehug": { canonical: "กอดความเจ็บปวด (Gentle Hug)", artists: ["mirrr"] },
  "ghost": { canonical: "ไม่ไปไหน (Ghost)", artists: ["mirrr"] },
  "glad": { canonical: "ดีใจด้วยนะ (Glad)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "good luck": { canonical: "โชคดีนะเพื่อน (Good Luck)", artists: ["lipta","ลิปตา"] },
  "good luck to the both of us": { canonical: "ขอให้เราทั้งคู่โชคดี (Good Luck to The Both of Us)", artists: ["tattoo colour"] },
  "good old days": { canonical: "วันเก่า (good old days)", artists: ["loserpop"] },
  "goodfella": { canonical: "เพื่อนพระเอก (Goodfella)", artists: ["polycat"] },
  "goodluck": { canonical: "โชคดีนะเพื่อน (Good Luck)", artists: ["lipta","ลิปตา"] },
  "goodlucktothebothofus": { canonical: "ขอให้เราทั้งคู่โชคดี (Good Luck to The Both of Us)", artists: ["tattoo colour"] },
  "goodolddays": { canonical: "วันเก่า (good old days)", artists: ["loserpop"] },
  "half an eyesight": { canonical: "ครึ่งสายตา (Half an Eyesight)", artists: ["sqweez animal"] },
  "halfaneyesight": { canonical: "ครึ่งสายตา (Half an Eyesight)", artists: ["sqweez animal"] },
  "halley comet": { canonical: "ดาวหางฮัลเลย์ (Halley's Comet)" },
  "halley's comet": { canonical: "ดาวหางฮัลเลย์ (Halley's Comet)" },
  "halleys comet": { canonical: "ดาวหางฮัลเลย์ (Halley's Comet)" },
  "happily missing you": { canonical: "สุขสันต์วันคิดถึง (Happily Missing You)", artists: ["bus"] },
  "happilymissingyou": { canonical: "สุขสันต์วันคิดถึง (Happily Missing You)", artists: ["bus"] },
  "heartwall": { canonical: "กำแพงหัวใจ (Heartwall)", artists: ["mirrr"] },
  "heavy rotation": { canonical: "เฮฟวี่โรเตชั่น (Heavy Rotation)", artists: ["bnk48","akb48"] },
  "heavyrotation": { canonical: "เฮฟวี่โรเตชั่น (Heavy Rotation)", artists: ["bnk48","akb48"] },
  "help me please": { canonical: "ช่วยไม่ได้ (Can't Help It)", artists: ["urboytj","urboy"] },
  "hesitate": { canonical: "ลังเล (Hesitate)", artists: ["pp krit","pp"] },
  "hey josh": { canonical: "Hey Josh! (พรุ่งนี้ต้องลืมเธอ)", artists: ["three man down"] },
  "hey josh!": { canonical: "Hey Josh! (พรุ่งนี้ต้องลืมเธอ)", artists: ["three man down"] },
  "heyjosh": { canonical: "Hey Josh! (พรุ่งนี้ต้องลืมเธอ)", artists: ["three man down"] },
  "hide": { canonical: "แค่เงา (Hide)", artists: ["jeff satur","jeff"] },
  "hide & seek": { canonical: "ซ่อนเธออยู่ในนั้น (Hide & Seek)", artists: ["safeplanet"] },
  "hide and seek": { canonical: "ซ่อนหา (Hide and Seek)", artists: ["tattoo colour"] },
  "hideandseek": { canonical: "ซ่อนหา (Hide and Seek)", artists: ["tattoo colour"] },
  "hurting": { canonical: "เจ็บอยู่ (Hurting)", artists: ["proxie"] },
  "i don't mind": { canonical: "แค่แอบหวัง (I Don't Mind)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "i dont mind": { canonical: "แค่แอบหวัง (I Don't Mind)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "i like myself the most": { canonical: "ชอบอยู่คนเดียว (I Like Myself The Most)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "i like us": { canonical: "ชอบตัวเองตอนอยู่กับเธอ (I Like Us)", artists: ["billkin"] },
  "i'm here": { canonical: "หนึ่งคนตรงนี้ (I'm here)" },
  "i'm not lonely": { canonical: "ฉันไม่เหงา (I'm Not Lonely)", artists: ["sqweez animal"] },
  "idontmind": { canonical: "แค่แอบหวัง (I Don't Mind)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "if i could": { canonical: "เริ่มก่อน (If I Could)", artists: ["proxie"] },
  "if i were you": { canonical: "หากว่าเราไม่คิดถึงกัน (If I Were You)", artists: ["zom marie","ส้ม มารี","the parkinson"] },
  "if you really love me": { canonical: "ถ้าเธอรักฉันจริง (If You Really Love Me)" },
  "ificould": { canonical: "เริ่มก่อน (If I Could)", artists: ["proxie"] },
  "ilikemyselfthemost": { canonical: "ชอบอยู่คนเดียว (I Like Myself The Most)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "ilikeus": { canonical: "ชอบตัวเองตอนอยู่กับเธอ (I Like Us)", artists: ["billkin"] },
  "im here": { canonical: "หนึ่งคนตรงนี้ (I'm here)" },
  "im not lonely": { canonical: "ฉันไม่เหงา (I'm Not Lonely)", artists: ["sqweez animal"] },
  "imhere": { canonical: "หนึ่งคนตรงนี้ (I'm here)" },
  "inchan tree": { canonical: "ต้นไม้ (Inchan Tree)", artists: ["scrubb"] },
  "inchantree": { canonical: "ต้นไม้ (Inchan Tree)", artists: ["scrubb"] },
  "infinity": { canonical: "ตลอดไปยังไม่พอ (Infinity)", artists: ["pixxie"] },
  "insomnia": { canonical: "เหงา เหงา (Insomnia)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "is this love": { canonical: "เปิดตัวเขา (Is This Love)", artists: ["three man down"] },
  "it ain't too late": { canonical: "อาจยังไม่สาย (It Ain't Too Late)", artists: ["sqweez animal"] },
  "it aint too late": { canonical: "อาจยังไม่สาย (It Ain't Too Late)", artists: ["sqweez animal"] },
  "it's me": { canonical: "นี่ฉันเองคนที่... (It's me)", artists: ["purpeech"] },
  "it's ok": { canonical: "ไม่เป็นไรที่รัก (It's ok)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "its me": { canonical: "นี่ฉันเองคนที่... (It's me)", artists: ["purpeech"] },
  "its ok": { canonical: "ไม่เป็นไรที่รัก (It's ok)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "itsok": { canonical: "ไม่เป็นไรที่รัก (It's ok)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "just being friendly": { canonical: "เพื่อนเล่น ไม่เล่นเพื่อน (Just Being Friendly)" },
  "just curious": { canonical: "ชอบใส่ใจ (Just Curious)", artists: ["bamm"] },
  "justbeingfriendly": { canonical: "เพื่อนเล่น ไม่เล่นเพื่อน (Just Being Friendly)" },
  "kab rod len": { canonical: "ขับรถเล่น (Kab Rod Len)", artists: ["anatomy rabbit"] },
  "kabrodlen": { canonical: "ขับรถเล่น (Kab Rod Len)", artists: ["anatomy rabbit"] },
  "kam tam jak khon kao": { canonical: "คำถามจากคนเก่า (Shouldn't ask)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "kam tam jak khon kao shouldnt ask": { canonical: "คำถามจากคนเก่า (Shouldn't ask)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "keep going": { canonical: "เดินต่อไป (Keep Going)", artists: ["youngohm"] },
  "keep it low key": { canonical: "ไม่รู้ดิ (Keep It Low Key)", artists: ["mirrr"] },
  "keepgoing": { canonical: "เดินต่อไป (Keep Going)", artists: ["youngohm"] },
  "keepitlowkey": { canonical: "ไม่รู้ดิ (Keep It Low Key)", artists: ["mirrr"] },
  "kidding": { canonical: "หรือฉันคิดไปเอง (Kidding?)", artists: ["zom marie","ส้ม มารี"] },
  "kidding?": { canonical: "หรือฉันคิดไปเอง (Kidding?)", artists: ["zom marie","ส้ม มารี"] },
  "kimi wa melody": { canonical: "เธอคือ...เมโลดี้ (Kimi wa Melody)", artists: ["bnk48","akb48"] },
  "kimiwamelody": { canonical: "เธอคือ...เมโลดี้ (Kimi wa Melody)", artists: ["bnk48","akb48"] },
  "know know": { canonical: "ทราบแล้วเปลี่ยน (Know Know)" },
  "know me": { canonical: "รู้ทั้งรู้ (Know Me)", artists: ["og-anic","oganic"] },
  "knowknow": { canonical: "ทราบแล้วเปลี่ยน (Know Know)" },
  "koisuru fortune cookie": { canonical: "คุกกี้เสี่ยงทาย (Koisuru Fortune Cookie)", artists: ["bnk48","akb48"] },
  "koisurufortunecookie": { canonical: "คุกกี้เสี่ยงทาย (Koisuru Fortune Cookie)", artists: ["bnk48","akb48"] },
  "kwam rak kum lung kor tua": { canonical: "ความรักกำลังก่อตัว", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "lean on": { canonical: "พิง (Lean On)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "leanon": { canonical: "พิง (Lean On)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "legends of a love story": { canonical: "เรื่องราวความรักในตำนาน (Legends of a Love Story)", artists: ["youngohm"] },
  "legendsofalovestory": { canonical: "เรื่องราวความรักในตำนาน (Legends of a Love Story)", artists: ["youngohm"] },
  "less is more": { canonical: "สิ่งเล็กน้อย (LESS IS MORE)", artists: ["4eve"] },
  "lessismore": { canonical: "สิ่งเล็กน้อย (LESS IS MORE)", artists: ["4eve"] },
  "let me love you": { canonical: "ถ้าเธอไม่อยากโชคร้ายเรื่องความรัก (Let Me Love You)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "let you go": { canonical: "ยอม..ปล่อย (Let You Go)" },
  "letmeloveyou": { canonical: "ถ้าเธอไม่อยากโชคร้ายเรื่องความรัก (Let Me Love You)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "letyougo": { canonical: "ยอม..ปล่อย (Let You Go)" },
  "lionheart": { canonical: "เจ้าป่า (Lionheart)", artists: ["bowkylion"] },
  "lonely boy": { canonical: "เหงาอย่างนี้สินะ (Lonely Boy)", artists: ["proxie"] },
  "lonelyboy": { canonical: "เหงาอย่างนี้สินะ (Lonely Boy)", artists: ["proxie"] },
  "loop": { canonical: "กลับมาที่เดิม (Loop)", artists: ["mirrr"] },
  "lost and found": { canonical: "ฉันก่อนเจอเธอ (Lost and Found)", artists: ["jeff satur","เจฟ ซาเตอร์"] },
  "love never lie": { canonical: "รักไม่หลอก (Love Never Lie)", artists: ["sqweez animal"] },
  "love you already": { canonical: "ฉันรักเธอแล้ว (love you already)", artists: ["loserpop"] },
  "loveneverlie": { canonical: "รักไม่หลอก (Love Never Lie)", artists: ["sqweez animal"] },
  "loveyoualready": { canonical: "ฉันรักเธอแล้ว (love you already)", artists: ["loserpop"] },
  "mars loner": { canonical: "สภาวะเดียวดายบนดาวอังคาร (Mars Loner)", artists: ["anatomy rabbit"] },
  "marsloner": { canonical: "สภาวะเดียวดายบนดาวอังคาร (Mars Loner)", artists: ["anatomy rabbit"] },
  "me tung": { canonical: "มีตังค์", artists: ["youngohm"] },
  "melatonin": { canonical: "นอนไม่หลับ (Melatonin)", artists: ["safeplanet"] },
  "melt": { canonical: "โต๊ะริม (Melt)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "metung": { canonical: "มีตังค์", artists: ["youngohm"] },
  "meun kam la": { canonical: "หมื่นคำลา", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "morning": { canonical: "เป็นไรไหม (Morning)", artists: ["lazyloxy"] },
  "mr everything": { canonical: "Mr. Everything (มิสเตอร์เอฟวรี่ติง)" },
  "mr. everything": { canonical: "Mr. Everything (มิสเตอร์เอฟวรี่ติง)" },
  "mreverything": { canonical: "Mr. Everything (มิสเตอร์เอฟวรี่ติง)" },
  "mutelu": { canonical: "มูเตลู (MUTELU)", artists: ["pixxie"] },
  "my crush": { canonical: "พี่ๆ ตัดแว่นให้หน่อย (My Crush)" },
  "my favorite": { canonical: "เจ้าของที่ (My Favorite)", artists: ["mirrr"] },
  "my vanilla": { canonical: "เพราะเธอนั้นเป็นเหมือนดั่งโลกทั้งใบ (My Vanilla)", artists: ["dept"] },
  "my worry": { canonical: "รู้เธอยังกังวล (My Worry)", artists: ["safeplanet"] },
  "mycrush": { canonical: "พี่ๆ ตัดแว่นให้หน่อย (My Crush)" },
  "myfavorite": { canonical: "เจ้าของที่ (My Favorite)", artists: ["mirrr"] },
  "myvanilla": { canonical: "เพราะเธอนั้นเป็นเหมือนดั่งโลกทั้งใบ (My Vanilla)", artists: ["dept"] },
  "myworry": { canonical: "รู้เธอยังกังวล (My Worry)", artists: ["safeplanet"] },
  "nakorn dara": { canonical: "นครดารา (Nakorn Dara)", artists: ["youngohm"] },
  "nakorndara": { canonical: "นครดารา (Nakorn Dara)", artists: ["youngohm"] },
  "new me": { canonical: "คนใหม่ (New Me)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "new world": { canonical: "โลกใบใหม่ (New World)", artists: ["safeplanet"] },
  "newme": { canonical: "คนใหม่ (New Me)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "newworld": { canonical: "โลกใบใหม่ (New World)", artists: ["safeplanet"] },
  "nicotine": { canonical: "นิโคติน (Nicotine)", artists: ["mirrr"] },
  "ninja": { canonical: "นินจา (Ninja)", artists: ["mirrr"] },
  "nittayasan": { canonical: "นิตยสาร (Nittayasan)", artists: ["anatomy rabbit"] },
  "no forever": { canonical: "ตลอดไปไม่มีจริง (NO FOREVER)", artists: ["mirrr"] },
  "no matter what": { canonical: "แค่ไหนแค่นั้น (NO MATTER WHAT)", artists: ["bus"] },
  "no!forever?": { canonical: "ตลอดไปไม่มีจริง (NO FOREVER)", artists: ["mirrr"] },
  "noforever": { canonical: "ตลอดไปไม่มีจริง (NO FOREVER)", artists: ["mirrr"] },
  "nomad's lullaby": { canonical: "ในวันพรุ่งนี้ขอให้เป็นวันที่ดี (Nomad's Lullaby)", artists: ["landokmai"] },
  "nomads lullaby": { canonical: "ในวันพรุ่งนี้ขอให้เป็นวันที่ดี (Nomad's Lullaby)", artists: ["landokmai"] },
  "nomatterwhat": { canonical: "แค่ไหนแค่นั้น (NO MATTER WHAT)", artists: ["bus"] },
  "not kidding": { canonical: "ไปล้อเล่นไกลๆ (Not Kidding)", artists: ["4eve"] },
  "not looking back": { canonical: "ไม่มองกลับหลัง (Not Looking Back)", artists: ["sqweez animal"] },
  "not my fault": { canonical: "ไม่เป็นรอง (Not My Fault)" },
  "not ok": { canonical: "ไม่ได้ก็ไม่เอา (NOT OK)", artists: ["pixxie"] },
  "not romantic": { canonical: "ทุกนาทีที่สวยงาม (Not Romantic)" },
  "notkidding": { canonical: "ไปล้อเล่นไกลๆ (Not Kidding)", artists: ["4eve"] },
  "notlookingback": { canonical: "ไม่มองกลับหลัง (Not Looking Back)", artists: ["sqweez animal"] },
  "notmyfault": { canonical: "ไม่เป็นรอง (Not My Fault)" },
  "notok": { canonical: "ไม่ได้ก็ไม่เอา (NOT OK)", artists: ["pixxie"] },
  "once": { canonical: "อีกครั้ง (once)", artists: ["loserpop"] },
  "only you can": { canonical: "ล้มแชมป์ (Only You Can)" },
  "ooh": { canonical: "เสนอตัว (Ooh!)", artists: ["pp krit","pp"] },
  "ooh!": { canonical: "เสนอตัว (Ooh!)", artists: ["pp krit","pp"] },
  "ordinary": { canonical: "จากกันด้วยดี (Ordinary)", artists: ["tilly birds"] },
  "our first day": { canonical: "วันแรกของวันที่เหลือ (Our First Day)", artists: ["4eve"] },
  "our sunset": { canonical: "ฟ้า (Our Sunset)", artists: ["landokmai"] },
  "ourfirstday": { canonical: "วันแรกของวันที่เหลือ (Our First Day)", artists: ["4eve"] },
  "oursunset": { canonical: "ฟ้า (Our Sunset)", artists: ["landokmai"] },
  "parsec": { canonical: "กาลครั้งหนึ่งบนโลก (Parsec)", artists: ["purpeech"] },
  "passing by": { canonical: "ผ่านตา (Passing By)", artists: ["three man down"] },
  "pistol": { canonical: "ปืน (Pistol)", artists: ["polycat"] },
  "pixxel": { canonical: "เพลงประจำวัน (PiXXeL)", artists: ["pixxie"] },
  "platonic love": { canonical: "เพื่อนสนิท (Platonic Love)", artists: ["three man down"] },
  "platoniclove": { canonical: "เพื่อนสนิท (Platonic Love)", artists: ["three man down"] },
  "please be true": { canonical: "ด้วยใจยินดี (Please be true)", artists: ["landokmai"] },
  "please please": { canonical: "กลับมาคบกันเถอะ (Please Please)", artists: ["billkin"] },
  "pleasebetrue": { canonical: "ด้วยใจยินดี (Please be true)", artists: ["landokmai"] },
  "pleaseplease": { canonical: "กลับมาคบกันเถอะ (Please Please)", artists: ["billkin"] },
  "png": { canonical: "บังเอิญพบทานตะวัน (.png)", artists: ["purpeech"] },
  "post-it": { canonical: "รู้กันแค่นี้ (post-it)", artists: ["bowkylion"] },
  "postit": { canonical: "รู้กันแค่นี้ (post-it)", artists: ["bowkylion"] },
  "pretend": { canonical: "เสแสร้ง (Pretend)", artists: ["paper planes"] },
  "promise me": { canonical: "รักเขาแทนฉันที (Promise Me)", artists: ["serious bacon"] },
  "promiseme": { canonical: "รักเขาแทนฉันที (Promise Me)", artists: ["serious bacon"] },
  "pull my heart": { canonical: "ดึงดัน (Pull My Heart)" },
  "pullmyheart": { canonical: "ดึงดัน (Pull My Heart)" },
  "quarantine": { canonical: "กักตัว (Quarantine)", artists: ["violette wautier","วี วิโอเลต"] },
  "rain wedding": { canonical: "เหมือนวิวาห์ (Rain Wedding)" },
  "rebound": { canonical: "เค้าก่อน (Rebound)", artists: ["urboytj","urboy"] },
  "recall": { canonical: "วาดไว้ (Recall)", artists: ["bowkylion","โบกี้ไลออน"] },
  "repeat": { canonical: "อยากเริ่มต้นใหม่กับคนเดิม (Repeat)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "restart": { canonical: "เริ่มใหม่ (Restart)", artists: ["sqweez animal"] },
  "river": { canonical: "ริเวอร์ (RIVER)", artists: ["bnk48"] },
  "rookie lover": { canonical: "มือสมัครรัก (Rookie Lover)", artists: ["bamm"] },
  "rookielover": { canonical: "มือสมัครรัก (Rookie Lover)", artists: ["bamm"] },
  "saa tuu": { canonical: "สาธุ (Saa-Tuu)", artists: ["milli"] },
  "saa-tuu": { canonical: "สาธุ (Saa-Tuu)", artists: ["milli"] },
  "saatuu": { canonical: "สาธุ (Saa-Tuu)", artists: ["milli"] },
  "sad move": { canonical: "ปล่อยจอย (Sad Move)", artists: ["bamm"] },
  "sad o'clock": { canonical: "ปล่อยจอย (Sad O'Clock)", artists: ["bamm"] },
  "sad oclock": { canonical: "ปล่อยจอย (Sad O'Clock)", artists: ["bamm"] },
  "sadoclock": { canonical: "ปล่อยจอย (Sad O'Clock)", artists: ["bamm"] },
  "safe zone": { canonical: "รู้งี้เป็นแฟนกันตั้งนานแล้ว (Safe Zone)", artists: ["billkin","pp krit","pp"] },
  "safezone": { canonical: "รู้งี้เป็นแฟนกันตั้งนานแล้ว (Safe Zone)", artists: ["billkin","pp krit","pp"] },
  "sai nam peung": { canonical: "สายน้ำผึ้ง", artists: ["youngohm"] },
  "sainampeung": { canonical: "สายน้ำผึ้ง", artists: ["youngohm"] },
  "same page": { canonical: "คิด(แต่ไม่)ถึง (Same Page?)" },
  "same page?": { canonical: "คิด(แต่ไม่)ถึง (Same Page?)" },
  "samepage": { canonical: "คิด(แต่ไม่)ถึง (Same Page?)" },
  "shonichi": { canonical: "วันแรก (Shonichi)", artists: ["bnk48","akb48"] },
  "shouldn't ask": { canonical: "คำถามจากคนเก่า (Shouldn't ask)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "shouldnt ask": { canonical: "คำถามจากคนเก่า (Shouldn't ask)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "shy": { canonical: "อาย (Shy)", artists: ["sqweez animal"] },
  "silent mode": { canonical: "คนไม่คุย (Silent Mode)" },
  "silentmode": { canonical: "คนไม่คุย (Silent Mode)" },
  "sincare": { canonical: "หากจะเพียงขอ (Sincare)", artists: ["purpeech"] },
  "skyline": { canonical: "กีดกัน (Skyline)", artists: ["billkin","บิวกิ้น"] },
  "slipped your mind": { canonical: "จำเก่ง (Slipped Your Mind)", artists: ["tilly birds","f.hero"] },
  "slippedyourmind": { canonical: "จำเก่ง (Slipped Your Mind)", artists: ["tilly birds","f.hero"] },
  "so long": { canonical: "พบกันใหม่ (So Long)", artists: ["polycat"] },
  "so what": { canonical: "คือราย (so what)", artists: ["bowkylion"] },
  "solong": { canonical: "พบกันใหม่ (So Long)", artists: ["polycat"] },
  "someone who cares": { canonical: "อย่าไปรักเขาเลยเธอ (Someone Who Cares)", artists: ["serious bacon"] },
  "someonewhocares": { canonical: "อย่าไปรักเขาเลยเธอ (Someone Who Cares)", artists: ["serious bacon"] },
  "somewhere": { canonical: "แค่วันพรุ่งนี้ที่ไม่มีเรา (Somewhere)", artists: ["dept"] },
  "sood gon": { canonical: "สุดก่อน", artists: ["milli"] },
  "sood-gon": { canonical: "สุดก่อน", artists: ["milli"] },
  "soodgon": { canonical: "สุดก่อน", artists: ["milli"] },
  "sowhat": { canonical: "คือราย (so what)", artists: ["bowkylion"] },
  "special one": { canonical: "โคตรพิเศษ (Special One)", artists: ["billkin"] },
  "specialone": { canonical: "โคตรพิเศษ (Special One)", artists: ["billkin"] },
  "status": { canonical: "เบื่อคนขี้เบื่อ (Status)", artists: ["tilly birds"] },
  "stay": { canonical: "รอหรือพอ (Stay)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "sticker": { canonical: "สติ๊กเกอร์ (Sticker)", artists: ["bodyslam"] },
  "still": [{ canonical: "ยังรอ (still)", artists: ["loserpop"] }, { canonical: "เกาะลอยฟ้า (Still)", artists: ["landokmai"] }],
  "stop": { canonical: "ตบปาก (STOP!)", artists: ["proxie"] },
  "stop!": { canonical: "ตบปาก (STOP!)", artists: ["proxie"] },
  "storage": { canonical: "เก็บไว้ในใจไม่พอ (Storage)", artists: ["maiyarap"] },
  "strangers": { canonical: "เคย (strangers)", artists: ["loserpop"] },
  "sunset": { canonical: "อย่างน้อย (Sunset)", artists: ["safeplanet"] },
  "super car care": { canonical: "SuperCarCare (ซุปเปอร์คาร์แคร์)", artists: ["tattoo colour"] },
  "supercarcare": { canonical: "SuperCarCare (ซุปเปอร์คาร์แคร์)", artists: ["tattoo colour"] },
  "surfing": { canonical: "รอยยิ้ม (Surfing)", artists: ["scrubb"] },
  "tapha": { canonical: "ตาฟา (Tapha)", artists: ["anatomy rabbit"] },
  "teardrops": { canonical: "เป็นเพราะฝน (Teardrops)", artists: ["polycat"] },
  "tears": { canonical: "แม้ว่าจะเหลือแค่เพียงน้ำตา (Tears)", artists: ["safeplanet"] },
  "tell her that i love": { canonical: "จะบอกเธอว่ารัก (Tell Her That I Love)" },
  "test me": { canonical: "วัดปะหล่ะ? (TEST ME)", artists: ["4eve"] },
  "testme": { canonical: "วัดปะหล่ะ? (TEST ME)", artists: ["4eve"] },
  "thararat": { canonical: "ธารารัตน์ (Thararat)", artists: ["youngohm"] },
  "the end": { canonical: "ปล่อยมือ (The End)", artists: ["safeplanet"] },
  "the heart": { canonical: "ในเมื่อใจ (The Heart)", artists: ["safeplanet"] },
  "the last kiss": { canonical: "จูบลา (The Last Kiss)", artists: ["youngohm"] },
  "the light in the city": { canonical: "แสงไฟ (The Light in the City)", artists: ["youngohm"] },
  "the light in the city (intro)": { canonical: "แสงไฟ (The Light in the City)", artists: ["youngohm"] },
  "the maze": { canonical: "สิ่งที่เธอฝากไว้ (The Maze)", artists: ["safeplanet"] },
  "the moment": { canonical: "ดั่งถูกกำหนดไว้ (The Moment)", artists: ["safeplanet"] },
  "the mountain": { canonical: "ไม่เคยเปลี่ยน (The Mountain)", artists: ["safeplanet"] },
  "the one": { canonical: "ผู้เดียว (The One)", artists: ["tilly birds"] },
  "the secret": { canonical: "ถ้าเธอได้รู้ (The Secret ∆)", artists: ["safeplanet"] },
  "the secret delta": { canonical: "ถ้าเธอได้รู้ (The Secret ∆)", artists: ["safeplanet"] },
  "the secret ∆": { canonical: "ถ้าเธอได้รู้ (The Secret ∆)", artists: ["safeplanet"] },
  "the wait": { canonical: "การรอคอย (THE WAIT8)", artists: ["safeplanet"] },
  "the wait 8": { canonical: "การรอคอย (THE WAIT8)", artists: ["safeplanet"] },
  "the wait8": { canonical: "การรอคอย (THE WAIT8)", artists: ["safeplanet"] },
  "the wind": { canonical: "พริบตา (The Wind)", artists: ["safeplanet"] },
  "theend": { canonical: "ปล่อยมือ (The End)", artists: ["safeplanet"] },
  "theheart": { canonical: "ในเมื่อใจ (The Heart)", artists: ["safeplanet"] },
  "thelastkiss": { canonical: "จูบลา (The Last Kiss)", artists: ["youngohm"] },
  "themaze": { canonical: "สิ่งที่เธอฝากไว้ (The Maze)", artists: ["safeplanet"] },
  "themoment": { canonical: "ดั่งถูกกำหนดไว้ (The Moment)", artists: ["safeplanet"] },
  "themountain": { canonical: "ไม่เคยเปลี่ยน (The Mountain)", artists: ["safeplanet"] },
  "theone": { canonical: "ผู้เดียว (The One)", artists: ["tilly birds"] },
  "thesecret": { canonical: "ถ้าเธอได้รู้ (The Secret ∆)", artists: ["safeplanet"] },
  "thewait8": { canonical: "การรอคอย (THE WAIT8)", artists: ["safeplanet"] },
  "thewind": { canonical: "พริบตา (The Wind)", artists: ["safeplanet"] },
  "thinking of you": { canonical: "ได้แต่นึกถึง (Thinking of You)", artists: ["only monday"] },
  "this time": { canonical: "ตั้งแต่มีเธอฉันมีความสุข (This Time)", artists: ["violette wautier","วี วิโอเลต"] },
  "thistime": { canonical: "ตั้งแต่มีเธอฉันมีความสุข (This Time)", artists: ["violette wautier","วี วิโอเลต"] },
  "tick tock": { canonical: "ติ๊กต๊อก (Tick Tock)", artists: ["palmy","ปาล์มมี่"] },
  "ticktock": { canonical: "ติ๊กต๊อก (Tick Tock)", artists: ["palmy","ปาล์มมี่"] },
  "time zone": { canonical: "เวลาเธอยิ้ม (Time Zone)", artists: ["three man down"] },
  "timezone": { canonical: "เวลาเธอยิ้ม (Time Zone)", artists: ["three man down"] },
  "to the day": { canonical: "วันที่สวยงาม (To The Day)", artists: ["safeplanet"] },
  "today last year": { canonical: "วันนี้เมื่อปีก่อน (Today, Last Year)", artists: ["moderndog"] },
  "today, last year": { canonical: "วันนี้เมื่อปีก่อน (Today, Last Year)", artists: ["moderndog"] },
  "todaylastyear": { canonical: "วันนี้เมื่อปีก่อน (Today, Last Year)", artists: ["moderndog"] },
  "too cute": { canonical: "เกินต้าน (Too Cute)", artists: ["pixxie"] },
  "too late": { canonical: "รักกันตอนเลิกกัน (Too Late)", artists: ["pixxie"] },
  "toocute": { canonical: "เกินต้าน (Too Cute)", artists: ["pixxie"] },
  "toolate": { canonical: "รักกันตอนเลิกกัน (Too Late)", artists: ["pixxie"] },
  "totheday": { canonical: "วันที่สวยงาม (To The Day)", artists: ["safeplanet"] },
  "traffic": { canonical: "ใจกระตุก (TRAFFIC)", artists: ["proxie"] },
  "true love": { canonical: "รักแท้ (True Love)", artists: ["nunew","นุนิว"] },
  "tsugi no season": { canonical: "ฤดูใหม่ (Tsugi no Season)", artists: ["bnk48","akb48"] },
  "tsuginoseason": { canonical: "ฤดูใหม่ (Tsugi no Season)", artists: ["bnk48","akb48"] },
  "turn around": { canonical: "กลับไปกลับมา (turn around)", artists: ["loserpop"] },
  "turnaround": { canonical: "กลับไปกลับมา (turn around)", artists: ["loserpop"] },
  "udon town": { canonical: "อุดรทาวน์ (Udon Town)", artists: ["anatomy rabbit"] },
  "udontown": { canonical: "อุดรทาวน์ (Udon Town)", artists: ["anatomy rabbit"] },
  "undeniable": { canonical: "จะรักดีไหม (Undeniable)", artists: ["sqweez animal"] },
  "unfriend zone": { canonical: "ใครเพื่อนแก (Unfriend Zone)", artists: ["bamm"] },
  "unfriendzone": { canonical: "ใครเพื่อนแก (Unfriend Zone)", artists: ["bamm"] },
  "unniversary": { canonical: "วันครบเลิก (UNNIVERSARY)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "unnoticed": { canonical: "ที่ไม่รัก (Unnoticed)", artists: ["proxie"] },
  "until then": { canonical: "ถ้าเราเจอกันอีก (Until Then)" },
  "untilthen": { canonical: "ถ้าเราเจอกันอีก (Until Then)" },
  "untold": [{ canonical: "บานปลาย (Best Wishes)" }, { canonical: "คิดถึงแต่ (Untold)", artists: ["bowkylion"] }],
  "villain": { canonical: "วายร้าย (Villain)", artists: ["urboytj","urboy"] },
  "voodoo potion": { canonical: "ทุกสิ่ง (Voodoo Potion)", artists: ["safeplanet"] },
  "voodoopotion": { canonical: "ทุกสิ่ง (Voodoo Potion)", artists: ["safeplanet"] },
  "warm up a curry": { canonical: "อุ่นแกง (Warm up a Curry)", artists: ["youngohm"] },
  "warmupacurry": { canonical: "อุ่นแกง (Warm up a Curry)", artists: ["youngohm"] },
  "warning": { canonical: "ระวังเสียใจ (Warning)", artists: ["violette wautier","วี วิโอเลต"] },
  "wasted": { canonical: "ของที่เธอไม่ต้องการ (Wasted)", artists: ["three man down"] },
  "whatever": { canonical: "ไม่ได้ก็ไม่เอา (Whatever)", artists: ["pixxie"] },
  "whatever will be , will be": { canonical: "ขอเธอจงผ่อนคลาย (Whatever Will Be, Will Be)", artists: ["safeplanet"] },
  "whatever will be will be": { canonical: "ขอเธอจงผ่อนคลาย (Whatever Will Be, Will Be)", artists: ["safeplanet"] },
  "where are you": { canonical: "ไปเถอะเธอ (Where Are You)", artists: ["three man down"] },
  "white flag": [{ canonical: "จำนน (White Flag)", artists: ["nont tanont","นนท์ ธนนท์","nont"] }, { canonical: "ยอม (White Flag)", artists: ["landokmai"] }],
  "whiteflag": { canonical: "จำนน (White Flag)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "why don't you stay": { canonical: "แค่เธอ (Why Don't You Stay)" },
  "why dont you stay": { canonical: "แค่เธอ (Why Don't You Stay)" },
  "whydontyoustay": { canonical: "แค่เธอ (Why Don't You Stay)", artists: ["jeff satur","jeff"] },
  "will you": { canonical: "จะรักฉันอยู่ไหม (Will You?)" },
  "will you marry me": { canonical: "แต่งงานกันนะ (Will You Marry Me?)", artists: ["lipta","ลิปตา"] },
  "will you?": { canonical: "จะรักฉันอยู่ไหม (Will You?)" },
  "woof": { canonical: "เอ๋ง (WOOF)", artists: ["bamm"] },
  "worth the wait": { canonical: "แค่เธอเข้ามา (Worth The Wait)" },
  "yellow leaf": { canonical: "ส่วนน้อย (Yellow Leaf)", artists: ["jeff satur","jeffsatur"] },
  "yellowleaf": { canonical: "ส่วนน้อย (Yellow Leaf)", artists: ["jeff satur","jeffsatur"] },
  "you had me at hello": { canonical: "เวลาเธอยิ้ม (You Had Me At Hello)", artists: ["polycat"] },
  "youhadmeathello": { canonical: "เวลาเธอยิ้ม (You Had Me At Hello)", artists: ["polycat"] },
  "young yaow": { canonical: "ยังเยาว์ (Young Yaow)", artists: ["anatomy rabbit"] },
  "youngyaow": { canonical: "ยังเยาว์ (Young Yaow)", artists: ["anatomy rabbit"] },
  "your arm": { canonical: "แขนซ้าย (Your Arm)", artists: ["bowkylion"] },
  "your ex": { canonical: "ค.ควาย (Your Ex)", artists: ["bowkylion"] },
  "your rules": { canonical: "เกม (Your Rules)", artists: ["mirrr"] },
  "your worst enemy": { canonical: "ศัตรูหัวใจ (Your Worst Enemy!)", artists: ["serious bacon"] },
  "your worst enemy!": { canonical: "ศัตรูหัวใจ (Your Worst Enemy!)", artists: ["serious bacon"] },
  "yourarm": { canonical: "แขนซ้าย (Your Arm)", artists: ["bowkylion"] },
  "yourex": { canonical: "ค.ควาย (Your Ex)", artists: ["bowkylion"] },
  "yourrules": { canonical: "เกม (Your Rules)", artists: ["mirrr"] },
  "yourworstenemy": { canonical: "ศัตรูหัวใจ (Your Worst Enemy!)", artists: ["serious bacon"] },
  "กลับมาคบกันเถอะ": { canonical: "กลับมาคบกันเถอะ (Please Please)", artists: ["billkin"] },
  "กลับมาที่เดิม": { canonical: "กลับมาที่เดิม (Loop)", artists: ["mirrr"] },
  "กลับไปกลับมา": { canonical: "กลับไปกลับมา (turn around)", artists: ["loserpop"] },
  "กอดความเจ็บปวด": { canonical: "กอดความเจ็บปวด (Gentle Hug)", artists: ["mirrr"] },
  "การรอคอย": { canonical: "การรอคอย (THE WAIT8)", artists: ["safeplanet"] },
  "การเดินทางที่สวยงาม": { canonical: "การเดินทางที่สวยงาม (A Beautiful Ride)", artists: ["billkin"] },
  "กาลครั้งหนึ่งบนโลก": { canonical: "กาลครั้งหนึ่งบนโลก (Parsec)", artists: ["purpeech"] },
  "กำแพงหัวใจ": { canonical: "กำแพงหัวใจ (Heartwall)", artists: ["mirrr"] },
  "กีดกัน": { canonical: "กีดกัน (Skyline)", artists: ["billkin"] },
  "ก่อนใคร": { canonical: "ก่อนใคร (1st)", artists: ["bowkylion"] },
  "ของที่เธอไม่ต้องการ": { canonical: "ของที่เธอไม่ต้องการ (Wasted)", artists: ["three man down"] },
  "ขอเธอจงผ่อนคลาย": { canonical: "ขอเธอจงผ่อนคลาย (Whatever Will Be, Will Be)", artists: ["safeplanet"] },
  "ขอให้เราทั้งคู่โชคดี": { canonical: "ขอให้เราทั้งคู่โชคดี (Good Luck to The Both of Us)", artists: ["tattoo colour"] },
  "ขับรถเล่น": { canonical: "ขับรถเล่น (Kab Rod Len)", artists: ["anatomy rabbit"] },
  "ข้อยกเว้น": { canonical: "ข้อยกเว้น (Exceptional)", artists: ["4eve"] },
  "ข้างกัน": { canonical: "ข้างกัน (City)", artists: ["three man down"] },
  "ค ควาย": { canonical: "ค.ควาย (Your Ex)", artists: ["bowkylion"] },
  "ค.ควาย": { canonical: "ค.ควาย (Your Ex)", artists: ["bowkylion"] },
  "คงต้องบอกลาแล้ว": { canonical: "คงต้องบอกลาแล้ว (Farewell)", artists: ["dept"] },
  "คนใหม่": { canonical: "คนใหม่ (New Me)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "คนใหม่เขาดูแลอยู่": { canonical: "คนใหม่เขาดูแลอยู่ (Close)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "คนไม่คุย": { canonical: "คนไม่คุย (Silent Mode)", artists: ["proxie"] },
  "ครึ่งสายตา": { canonical: "ครึ่งสายตา (Half an Eyesight)", artists: ["sqweez animal"] },
  "คลั่งรัก": { canonical: "คลั่งรัก (Crazy)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "ความรักกำลังก่อตัว": { canonical: "ความรักกำลังก่อตัว", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "คำถามจากคนเก่า": { canonical: "คำถามจากคนเก่า (Shouldn't ask)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "คิดถึงแต่": { canonical: "คิดถึงแต่ (Untold)", artists: ["bowkylion"] },
  "คือราย": { canonical: "คือราย (so what)", artists: ["bowkylion"] },
  "ค้นใจ": { canonical: "C.I.A. (ค้นใจ)", artists: ["d2b"] },
  "งอนละ": { canonical: "งอนละ (Boo)", artists: ["pixxie"] },
  "จะรักดีไหม": { canonical: "จะรักดีไหม (Undeniable)", artists: ["sqweez animal"] },
  "จำนน": { canonical: "จำนน (White Flag)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "จำเก่ง": { canonical: "จำเก่ง (Slipped Your Mind)", artists: ["tilly birds","f.hero"] },
  "จูบลา": { canonical: "จูบลา (The Last Kiss)", artists: ["youngohm"] },
  "ฉันจะฉาปเธอ": { canonical: "ฉันจะฉาปเธอ (Curse)", artists: ["bamm"] },
  "ฉันจะสาปเธอ": { canonical: "ฉันจะฉาปเธอ (Curse)", artists: ["bamm"] },
  "ฉันรักเธอแล้ว": { canonical: "ฉันรักเธอแล้ว (love you already)", artists: ["loserpop"] },
  "ฉันไม่เหงา": { canonical: "ฉันไม่เหงา (I'm Not Lonely)", artists: ["sqweez animal"] },
  "ชน": { canonical: "ชน (Crush)", artists: ["proxie"] },
  "ชอบตัวเองตอนอยู่กับเธอ": { canonical: "ชอบตัวเองตอนอยู่กับเธอ (I Like Us)", artists: ["billkin"] },
  "ชอบอยู่คนเดียว": { canonical: "ชอบอยู่คนเดียว (I Like Myself The Most)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "ชาตินี้พอ": { canonical: "ชาตินี้พอ (Cameo)", artists: ["mirrr"] },
  "ซิ่ง": { canonical: "ซิ่ง (Friday On The High Way)", artists: ["polycat"] },
  "ซ่อน (ไม่) หา": { canonical: "ซ่อน (ไม่) หา (Ghost)", artists: ["jeff satur","jeffsatur"] },
  "ซ่อนเธออยู่ในนั้น": { canonical: "ซ่อนเธออยู่ในนั้น (Hide & Seek)", artists: ["safeplanet"] },
  "ซ่อนไม่หา": { canonical: "ซ่อน (ไม่) หา (Ghost)", artists: ["jeff satur","jeffsatur"] },
  "ดอกไม้ไฟ": { canonical: "ดอกไม้ไฟ (Firework)", artists: ["mirrr"] },
  "ดั่งถูกกำหนดไว้": { canonical: "ดั่งถูกกำหนดไว้ (The Moment)", artists: ["safeplanet"] },
  "ดาวตก": { canonical: "ดาวตก (fall)", artists: ["loserpop"] },
  "ดีใจด้วยนะ": { canonical: "ดีใจด้วยนะ (Glad)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "ด้วยใจยินดี": { canonical: "ด้วยใจยินดี (Please be true)", artists: ["landokmai"] },
  "ตบปาก": { canonical: "ตบปาก (STOP!)", artists: ["proxie"] },
  "ตลอดไปยังไม่พอ": { canonical: "ตลอดไปยังไม่พอ (Infinity)", artists: ["pixxie"] },
  "ตลอดไปไม่มีจริง": { canonical: "ตลอดไปไม่มีจริง (NO FOREVER)", artists: ["mirrr"] },
  "ตาฟา": { canonical: "ตาฟา (Tapha)", artists: ["anatomy rabbit"] },
  "ติ๊กต๊อก": { canonical: "ติ๊กต๊อก (Tick Tock)", artists: ["palmy","ปาล์มมี่"] },
  "ต้นไม้": { canonical: "ต้นไม้ (Inchan Tree)", artists: ["scrubb"] },
  "ถ้าเธอได้รู้": { canonical: "ถ้าเธอได้รู้ (The Secret ∆)", artists: ["safeplanet"] },
  "ถ้าเธอไม่อยากโชคร้ายเรื่องความรัก": { canonical: "ถ้าเธอไม่อยากโชคร้ายเรื่องความรัก (Let Me Love You)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "ทราบแล้วเปลี่ยน": { canonical: "ทราบแล้วเปลี่ยน (attention)", artists: ["bowkylion"] },
  "ทางที่ดี": { canonical: "ทางที่ดี (butterscotch)", artists: ["loserpop"] },
  "ทิวาสวัสดิ์": { canonical: "ทิวาสวัสดิ์ (Afternoon)", artists: ["bowkylion"] },
  "ทิ้งไว้อย่างพอใจ": { canonical: "ทิ้งไว้อย่างพอใจ (Consoled)", artists: ["purpeech"] },
  "ที่ไม่รัก": { canonical: "ที่ไม่รัก (Unnoticed)", artists: ["proxie"] },
  "ทุกนาทีที่สวยงาม": { canonical: "ทุกนาทีที่สวยงาม (Always With Me)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "ทุกวัน": { canonical: "ทุกวัน (Everyday)", artists: ["scrubb"] },
  "ทุกสิ่ง": { canonical: "ทุกสิ่ง (Voodoo Potion)", artists: ["safeplanet"] },
  "ธารารัตน์": { canonical: "ธารารัตน์ (Thararat)", artists: ["youngohm"] },
  "นครดารา": { canonical: "นครดารา (Nakorn Dara)", artists: ["youngohm"] },
  "นอนไม่หลับ": { canonical: "นอนไม่หลับ (Melatonin)", artists: ["safeplanet"] },
  "นิตยสาร": { canonical: "นิตยสาร (Nittayasan)", artists: ["anatomy rabbit"] },
  "นินจา": { canonical: "นินจา (Ninja)", artists: ["mirrr"] },
  "นิโคติน": { canonical: "นิโคติน (Nicotine)", artists: ["mirrr"] },
  "นี่ฉันเองคนที่": { canonical: "นี่ฉันเองคนที่... (It's me)", artists: ["purpeech"] },
  "บังเอิญพบทานตะวัน": { canonical: "บังเอิญพบทานตะวัน (.png)", artists: ["purpeech"] },
  "บานปลาย": { canonical: "บานปลาย (best wishes)", artists: ["bowkylion"] },
  "บารมีแห่งวังน้ำเย็น": { canonical: "บารมีแห่งวังน้ำเย็น", artists: ["ก้อง ห้วยไร่"] },
  "ปล่อยจอย": { canonical: "ปล่อยจอย (Sad O'Clock)", artists: ["bamm"] },
  "ปล่อยมือ": { canonical: "ปล่อยมือ (The End)", artists: ["safeplanet"] },
  "ปืน": { canonical: "ปืน (Pistol)", artists: ["polycat"] },
  "ผู้เดียว": { canonical: "ผู้เดียว (The One)", artists: ["tilly birds"] },
  "ผ้าพันแผล": { canonical: "ผ้าพันแผล (Bandage)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "ฝัง จำ จม": { canonical: "ฝัง จำ จม (Fung Jum Jom)", artists: ["silly fools"] },
  "ฝังจำจม": { canonical: "ฝัง จำ จม (Fung Jum Jom)", artists: ["silly fools"] },
  "พบกันใหม่": { canonical: "พบกันใหม่ (So Long)", artists: ["polycat"] },
  "พริบตา": { canonical: "พริบตา (The Wind)", artists: ["safeplanet"] },
  "พรุ่งนี้ต้องลืมเธอ": { canonical: "Hey Josh! (พรุ่งนี้ต้องลืมเธอ)", artists: ["three man down"] },
  "พิง": { canonical: "พิง (Lean On)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "ภักดี": { canonical: "ภักดี (Faith)", artists: ["polycat"] },
  "ภาพถ่ายวันวาน": { canonical: "ภาพถ่ายวันวาน (1920)", artists: ["purpeech"] },
  "มันเป็นใคร": { canonical: "มันเป็นใคร (Alright)", artists: ["polycat"] },
  "มีตังค์": { canonical: "มีตังค์", artists: ["youngohm"] },
  "มือสมัครรัก": { canonical: "มือสมัครรัก (Rookie Lover)", artists: ["bamm"] },
  "มูเตลู": { canonical: "มูเตลู (MUTELU)", artists: ["pixxie"] },
  "ยอม": { canonical: "ยอม (White Flag)", artists: ["landokmai"] },
  "ยังรอ": { canonical: "ยังรอ (still)", artists: ["loserpop"] },
  "ยังเยาว์": { canonical: "ยังเยาว์ (Young Yaow)", artists: ["anatomy rabbit"] },
  "ยิ้มมา": { canonical: "ยิ้มมา (Crush)", artists: ["bowkylion"] },
  "รอยยิ้ม": { canonical: "รอยยิ้ม (Surfing)", artists: ["scrubb"] },
  "รอหรือพอ": { canonical: "รอหรือพอ (Stay)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "รักกันตอนเลิกกัน": { canonical: "รักกันตอนเลิกกัน (Too Late)", artists: ["pixxie"] },
  "รักบ้าบอ": { canonical: "รักบ้าบอ (Crazy Love)", artists: ["proxie"] },
  "รักเขาแทนฉันที": { canonical: "รักเขาแทนฉันที (Promise Me)", artists: ["serious bacon"] },
  "รักไปร้องไห้ไป": { canonical: "รักไปร้องไห้ไป (Awesome Love)", artists: ["bowkylion"] },
  "รักไม่หลอก": { canonical: "รักไม่หลอก (Love Never Lie)", artists: ["sqweez animal"] },
  "รู้กันแค่นี้": { canonical: "รู้กันแค่นี้ (post-it)", artists: ["bowkylion"] },
  "รู้งี้เป็นแฟนกันตั้งนานแล้ว": { canonical: "รู้งี้เป็นแฟนกันตั้งนานแล้ว (Safe Zone)", artists: ["billkin","pp krit","pp"] },
  "รู้เธอยังกังวล": { canonical: "รู้เธอยังกังวล (My Worry)", artists: ["safeplanet"] },
  "ฤดู": { canonical: "ฤดู (Cycle of Love)", artists: ["dept"] },
  "ฤดูฝัน": { canonical: "ฤดูฝัน (Drizzle)", artists: ["landokmai"] },
  "ฤดูหนาว": { canonical: "ฤดูหนาว (Bangkok Winter)", artists: ["tilly birds","paam"] },
  "ลังเล": { canonical: "ลังเล (Hesitate)", artists: ["pp krit","pp"] },
  "ลืมไปแล้วว่าลืมยังไง": { canonical: "ลืมไปแล้วว่าลืมยังไง (Fade)", artists: ["jeff satur","jeff"] },
  "ลืมไปแล้วหรือยัง": { canonical: "ลืมไปแล้วว่าลืมยังไง (Fade)", artists: ["jeff satur","jeff"] },
  "ลู่วิ่ง": { canonical: "ลู่วิ่ง (Can't Keep Up)", artists: ["tilly birds"] },
  "วัดปะหล่ะ": { canonical: "วัดปะหล่ะ? (TEST ME)", artists: ["4eve"] },
  "วัดปะหล่ะ?": { canonical: "วัดปะหล่ะ? (TEST ME)", artists: ["4eve"] },
  "วัดป่ะหล่ะ": { canonical: "วัดปะหล่ะ? (TEST ME)", artists: ["4eve"] },
  "วัดป่ะหล่ะ?": { canonical: "วัดปะหล่ะ? (TEST ME)", artists: ["4eve"] },
  "วันครบเลิก": { canonical: "วันครบเลิก (UNNIVERSARY)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "วันที่สวยงาม": { canonical: "วันที่สวยงาม (To The Day)", artists: ["safeplanet"] },
  "วันนี้เมื่อปีก่อน": { canonical: "วันนี้เมื่อปีก่อน (Today, Last Year)", artists: ["moderndog"] },
  "วันเก่า": { canonical: "วันเก่า (good old days)", artists: ["loserpop"] },
  "วันแรกของวันที่เหลือ": { canonical: "วันแรกของวันที่เหลือ (Our First Day)", artists: ["4eve"] },
  "วาดไว้": { canonical: "วาดไว้ (recall)", artists: ["bowkylion"] },
  "ศัตรูหัวใจ": { canonical: "ศัตรูหัวใจ (Your Worst Enemy!)", artists: ["serious bacon"] },
  "สติ๊กเกอร์": { canonical: "สติ๊กเกอร์ (Sticker)", artists: ["bodyslam"] },
  "สถานะเบลอ": { canonical: "สถานะเบลอ (Blurrr)", artists: ["proxie"] },
  "สบายดี": { canonical: "สบายดี (Alright)", artists: ["purpeech"] },
  "สภาวะเดียวดายบนดาวอังคาร": { canonical: "สภาวะเดียวดายบนดาวอังคาร (Mars Loner)", artists: ["anatomy rabbit"] },
  "สาธุ": { canonical: "สาธุ (Saa-Tuu)", artists: ["milli"] },
  "สายตาหลอกกันไม่ได้": { canonical: "สายตาหลอกกันไม่ได้ (Eyes Don't Lie)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "สายน้ำผึ้ง": { canonical: "สายน้ำผึ้ง", artists: ["youngohm"] },
  "สิ่งที่เธอฝากไว้": { canonical: "สิ่งที่เธอฝากไว้ (The Maze)", artists: ["safeplanet"] },
  "สิ่งเล็กน้อย": { canonical: "สิ่งเล็กน้อย (LESS IS MORE)", artists: ["4eve"] },
  "สุขสันต์วันคิดถึง": { canonical: "สุขสันต์วันคิดถึง (Happily Missing You)", artists: ["bus"] },
  "สุดก่อน": { canonical: "สุดก่อน", artists: ["milli"] },
  "ส่วนน้อย": { canonical: "ส่วนน้อย (Yellow Leaf)", artists: ["jeff satur","jeffsatur"] },
  "หมดนี้ให้เธอ": { canonical: "หมดนี้ให้เธอ (All In)", artists: ["dept"] },
  "หมื่นคำลา": { canonical: "หมื่นคำลา", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "หยดน้ำตา": { canonical: "หยดน้ำตา (TEARS)", artists: ["4eve"] },
  "หยุดสักที": { canonical: "หยุดสักที (Cola)", artists: ["dept"] },
  "หากจะเพียงขอ": { canonical: "หากจะเพียงขอ (Sincare)", artists: ["purpeech"] },
  "อยากเริ่มต้นใหม่กับคนเดิม": { canonical: "อยากเริ่มต้นใหม่กับคนเดิม (Repeat)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "อย่างน้อย": { canonical: "อย่างน้อย (Sunset)", artists: ["safeplanet"] },
  "อย่าพี่น้อง": { canonical: "อย่าพี่น้อง (Cut Me Off)", artists: ["tilly birds"] },
  "อย่าไปรักเขาเลยเธอ": { canonical: "อย่าไปรักเขาเลยเธอ (Someone Who Cares)", artists: ["serious bacon"] },
  "อาจยังไม่สาย": { canonical: "อาจยังไม่สาย (It Ain't Too Late)", artists: ["sqweez animal"] },
  "อาย": { canonical: "อาย (Shy)", artists: ["sqweez animal"] },
  "อีกครั้ง": { canonical: "อีกครั้ง", artists: ["getsunova"] },
  "อีกสักครั้ง": { canonical: "อีกสักครั้ง (Another Day)", artists: ["sqweez animal"] },
  "อุดรทาวน์": { canonical: "อุดรทาวน์ (Udon Town)", artists: ["anatomy rabbit"] },
  "อุ่นแกง": { canonical: "อุ่นแกง (Warm up a Curry)", artists: ["youngohm"] },
  "เกม": { canonical: "เกม (Your Rules)", artists: ["mirrr"] },
  "เกาะลอยฟ้า": { canonical: "เกาะลอยฟ้า (Still)", artists: ["landokmai"] },
  "เกินต้าน": { canonical: "เกินต้าน (Too Cute)", artists: ["pixxie"] },
  "เกือบเป็นแฟน": { canonical: "เกือบเป็นแฟน (Close Enough)", artists: ["bamm"] },
  "เก่งแต่เรื่องคนอื่น": { canonical: "เก่งแต่เรื่องคนอื่น (Expert)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "เคย": { canonical: "เคย (strangers)", artists: ["loserpop"] },
  "เจ็บอยู่": { canonical: "เจ็บอยู่ (Hurting)", artists: ["proxie"] },
  "เจ้าของที่": { canonical: "เจ้าของที่ (My Favorite)", artists: ["mirrr"] },
  "เจ้าป่า": { canonical: "เจ้าป่า (Lionheart)", artists: ["bowkylion"] },
  "เดลิเวอรี่": { canonical: "เดลิเวอรี่ (Delivery)", artists: ["labanoon"] },
  "เดอะแบก": { canonical: "เดอะแบก (Baggage)", artists: ["tilly birds"] },
  "เดินต่อไป": { canonical: "เดินต่อไป (Keep Going)", artists: ["youngohm"] },
  "เด็ด": { canonical: "เด็ด (DED)", artists: ["pixxie"] },
  "เธอมีคนเดียวบนโลก": { canonical: "เธอมีคนเดียวบนโลก (AIN'T NO OTHER ONE)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "เธอเก่งที่สุดแล้ว": { canonical: "เธอเก่งที่สุดแล้ว (bammBOO)", artists: ["bamm"] },
  "เธอเองจะรู้บ้างไหม": { canonical: "เธอเองจะรู้บ้างไหม (Ex)", artists: ["mirrr"] },
  "เป็นเพราะฝน": { canonical: "เป็นเพราะฝน (Teardrops)", artists: ["polycat"] },
  "เพราะเธอนั้นเป็นเหมือนดั่งโลกทั้งใบ": { canonical: "เพราะเธอนั้นเป็นเหมือนดั่งโลกทั้งใบ (My Vanilla)", artists: ["dept"] },
  "เพลงประจำวัน": { canonical: "เพลงประจำวัน (PiXXeL)", artists: ["pixxie"] },
  "เพลงรักเพลงแรก": { canonical: "เพลงรักเพลงแรก (Blooming)", artists: ["landokmai"] },
  "เพียงเธอ": { canonical: "เพียงเธอ (Always)", artists: ["safeplanet"] },
  "เพื่อนกันไม่เลิกกัน": { canonical: "เพื่อนกันไม่เลิกกัน (Close Friend)", artists: ["bamm"] },
  "เพื่อนดีเด่น": { canonical: "เพื่อนดีเด่น (BEST FRIEND 4EVER)", artists: ["serious bacon"] },
  "เพื่อนพระเอก": { canonical: "เพื่อนพระเอก (Goodfella)", artists: ["polycat"] },
  "เพื่อนสนิท": { canonical: "เพื่อนสนิท (Platonic Love)", artists: ["three man down"] },
  "เพื่อนไม่จริง": { canonical: "เพื่อนไม่จริง (Forever Mate)", artists: ["polycat"] },
  "เมื่อไหร่ที่คิดถึงเธอ": { canonical: "เมื่อไหร่ที่คิดถึงเธอ (Echo)", artists: ["landokmai"] },
  "เริ่มก่อน": { canonical: "เริ่มก่อน (If I Could)", artists: ["proxie"] },
  "เริ่มใหม่": { canonical: "เริ่มใหม่ (Restart)", artists: ["sqweez animal"] },
  "เรื่องราวความรักในตำนาน": { canonical: "เรื่องราวความรักในตำนาน (Legends of a Love Story)", artists: ["youngohm"] },
  "เลี้ยงไข้": { canonical: "เลี้ยงไข้ (fever)", artists: ["bowkylion"] },
  "เวลาเธอยิ้ม": { canonical: "เวลาเธอยิ้ม (You Had Me At Hello)", artists: ["polycat"] },
  "เสนอตัว": { canonical: "เสนอตัว (Ooh!)", artists: ["pp krit","pp"] },
  "เหงา เหงา": { canonical: "เหงา เหงา (Insomnia)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "เหงาอย่างนี้สินะ": { canonical: "เหงาอย่างนี้สินะ (Lonely Boy)", artists: ["proxie"] },
  "เหงาเหงา": { canonical: "เหงา เหงา (Insomnia)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "เหวี่ยง": { canonical: "เหวี่ยง (Across The Worlds)", artists: ["safeplanet"] },
  "เอ๋ง": { canonical: "เอ๋ง (WOOF)", artists: ["bamm"] },
  "แขนซ้าย": { canonical: "แขนซ้าย (Your Arm)", artists: ["bowkylion"] },
  "แค่น้องชาย": { canonical: "แค่น้องชาย (brother zone)", artists: ["bus"] },
  "แค่วันพรุ่งนี้ที่ไม่มีเรา": { canonical: "แค่วันพรุ่งนี้ที่ไม่มีเรา (Somewhere)", artists: ["dept"] },
  "แค่เงา": { canonical: "แค่เงา (Hide)", artists: ["jeff satur","jeff"] },
  "แค่เธอ": { canonical: "แค่เธอ (Why Don't You Stay)", artists: ["jeff satur","jeff"] },
  "แค่แอบหวัง": { canonical: "แค่แอบหวัง (I Don't Mind)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "แค่ไหนแค่นั้น": { canonical: "แค่ไหนแค่นั้น (NO MATTER WHAT)", artists: ["bus"] },
  "แน่ใจไหม": { canonical: "แน่ใจไหม (Are You Sure?)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "แปลไม่ออก": { canonical: "แปลไม่ออก (Can't Translate)", artists: ["billkin"] },
  "แป๊บนึง": { canonical: "แป๊บนึง (Can You Stay?)", artists: ["serious bacon"] },
  "แม้ว่าจะเหลือแค่เพียงน้ำตา": { canonical: "แม้ว่าจะเหลือแค่เพียงน้ำตา (Tears)", artists: ["safeplanet"] },
  "แสงไฟ": { canonical: "แสงไฟ (The Light in the City)", artists: ["youngohm"] },
  "โคตรพิเศษ": { canonical: "โคตรพิเศษ (Special One)", artists: ["billkin"] },
  "โดนเทแต่เท่อยู่": { canonical: "โดนเทแต่เท่อยู่ (2cool2care)", artists: ["bamm"] },
  "โต๊ะริม": { canonical: "โต๊ะริม (melt)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "โลกอีกใบ": { canonical: "โลกอีกใบ (Bubble)", artists: ["zom marie","ส้ม มารี"] },
  "โลกใบใหม่": { canonical: "โลกใบใหม่ (New World)", artists: ["safeplanet"] },
  "ใครเพื่อนแก": { canonical: "ใครเพื่อนแก (Unfriend Zone)", artists: ["bamm"] },
  "ใจกระตุก": { canonical: "ใจกระตุก (TRAFFIC)", artists: ["proxie"] },
  "ในวันพรุ่งนี้ขอให้เป็นวันที่ดี": { canonical: "ในวันพรุ่งนี้ขอให้เป็นวันที่ดี (Nomad's Lullaby)", artists: ["landokmai"] },
  "ในเมื่อใจ": { canonical: "ในเมื่อใจ (The Heart)", artists: ["safeplanet"] },
  "ไปล้อเล่นไกลๆ": { canonical: "ไปล้อเล่นไกลๆ (Not Kidding)", artists: ["4eve"] },
  "ไฟเย็น": { canonical: "ไฟเย็น (Cold Fire)", artists: ["youngohm"] },
  "ไม่ปล่อยมือ": { canonical: "ไม่ปล่อยมือ (Coming of Age)", artists: ["billkin","pp krit","pp"] },
  "ไม่มองกลับหลัง": { canonical: "ไม่มองกลับหลัง (Not Looking Back)", artists: ["sqweez animal"] },
  "ไม่รู้ดิ": { canonical: "ไม่รู้ดิ (Keep It Low Key)", artists: ["mirrr"] },
  "ไม่อยากเหงาแล้ว": { canonical: "ไม่อยากเหงาแล้ว (Call Me)", artists: ["ink waruntorn","อิ้งค์ วรันธร","ink"] },
  "ไม่เคยเปลี่ยน": { canonical: "ไม่เคยเปลี่ยน (The Mountain)", artists: ["safeplanet"] },
  "ไม่เปลี่ยนเลย": { canonical: "ไม่เปลี่ยนเลย (Best Luck)", artists: ["fellow fellow","fellowfellow"] },
  "ไม่เป็นไรที่รัก": { canonical: "ไม่เป็นไรที่รัก (It's ok)", artists: ["nont tanont","นนท์ ธนนท์","nont"] },
  "ไม่ได้ก็ไม่เอา": { canonical: "ไม่ได้ก็ไม่เอา (Whatever)", artists: ["pixxie"] },
  "ไม่ไปไหน": { canonical: "ไม่ไปไหน (Ghost)", artists: ["mirrr"] },
};
